<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\AlbumRestrictionObject;

/**
 * Builder for model AlbumRestrictionObject
 *
 * @see AlbumRestrictionObject
 */
class AlbumRestrictionObjectBuilder
{
    /**
     * @var AlbumRestrictionObject
     */
    private $instance;

    private function __construct(AlbumRestrictionObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Album Restriction Object Builder object.
     */
    public static function init(): self
    {
        return new self(new AlbumRestrictionObject());
    }

    /**
     * Sets reason field.
     *
     * @param string|null $value
     */
    public function reason(?string $value): self
    {
        $this->instance->setReason($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Album Restriction Object object.
     */
    public function build(): AlbumRestrictionObject
    {
        return CoreHelper::clone($this->instance);
    }
}
