<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\AlbumBase;
use SpotifyWebApiLib\Models\AlbumRestrictionObject;
use SpotifyWebApiLib\Models\ExternalUrlObject;
use SpotifyWebApiLib\Models\ImageObject;

/**
 * Builder for model AlbumBase
 *
 * @see AlbumBase
 */
class AlbumBaseBuilder
{
    /**
     * @var AlbumBase
     */
    private $instance;

    private function __construct(AlbumBase $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Album Base Builder object.
     *
     * @param string $albumType
     * @param int $totalTracks
     * @param string[] $availableMarkets
     * @param ExternalUrlObject $externalUrls
     * @param string $href
     * @param string $id
     * @param ImageObject[] $images
     * @param string $name
     * @param string $releaseDate
     * @param string $releaseDatePrecision
     * @param string $type
     * @param string $uri
     */
    public static function init(
        string $albumType,
        int $totalTracks,
        array $availableMarkets,
        ExternalUrlObject $externalUrls,
        string $href,
        string $id,
        array $images,
        string $name,
        string $releaseDate,
        string $releaseDatePrecision,
        string $type,
        string $uri
    ): self {
        return new self(new AlbumBase(
            $albumType,
            $totalTracks,
            $availableMarkets,
            $externalUrls,
            $href,
            $id,
            $images,
            $name,
            $releaseDate,
            $releaseDatePrecision,
            $type,
            $uri
        ));
    }

    /**
     * Sets restrictions field.
     *
     * @param AlbumRestrictionObject|null $value
     */
    public function restrictions(?AlbumRestrictionObject $value): self
    {
        $this->instance->setRestrictions($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Album Base object.
     */
    public function build(): AlbumBase
    {
        return CoreHelper::clone($this->instance);
    }
}
