<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\AlbumObject;
use SpotifyWebApiLib\Models\AlbumRestrictionObject;
use SpotifyWebApiLib\Models\CopyrightObject;
use SpotifyWebApiLib\Models\ExternalIdObject;
use SpotifyWebApiLib\Models\ExternalUrlObject;
use SpotifyWebApiLib\Models\ImageObject;
use SpotifyWebApiLib\Models\PagingSimplifiedTrackObject;
use SpotifyWebApiLib\Models\SimplifiedArtistObject;

/**
 * Builder for model AlbumObject
 *
 * @see AlbumObject
 */
class AlbumObjectBuilder
{
    /**
     * @var AlbumObject
     */
    private $instance;

    private function __construct(AlbumObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Album Object Builder object.
     *
     * @param string $albumType
     * @param int $totalTracks
     * @param string[] $availableMarkets
     * @param ExternalUrlObject $externalUrls
     * @param string $href
     * @param string $id
     * @param ImageObject[] $images
     * @param string $name
     * @param string $releaseDate
     * @param string $releaseDatePrecision
     * @param string $type
     * @param string $uri
     * @param SimplifiedArtistObject[] $artists
     * @param PagingSimplifiedTrackObject $tracks
     * @param CopyrightObject[] $copyrights
     * @param ExternalIdObject $externalIds
     * @param string[] $genres
     * @param string $label
     * @param int $popularity
     */
    public static function init(
        string $albumType,
        int $totalTracks,
        array $availableMarkets,
        ExternalUrlObject $externalUrls,
        string $href,
        string $id,
        array $images,
        string $name,
        string $releaseDate,
        string $releaseDatePrecision,
        string $type,
        string $uri,
        array $artists,
        PagingSimplifiedTrackObject $tracks,
        array $copyrights,
        ExternalIdObject $externalIds,
        array $genres,
        string $label,
        int $popularity
    ): self {
        return new self(new AlbumObject(
            $albumType,
            $totalTracks,
            $availableMarkets,
            $externalUrls,
            $href,
            $id,
            $images,
            $name,
            $releaseDate,
            $releaseDatePrecision,
            $type,
            $uri,
            $artists,
            $tracks,
            $copyrights,
            $externalIds,
            $genres,
            $label,
            $popularity
        ));
    }

    /**
     * Sets restrictions field.
     *
     * @param AlbumRestrictionObject|null $value
     */
    public function restrictions(?AlbumRestrictionObject $value): self
    {
        $this->instance->setRestrictions($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Album Object object.
     */
    public function build(): AlbumObject
    {
        return CoreHelper::clone($this->instance);
    }
}
