<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\AudioAnalysisObject;
use SpotifyWebApiLib\Models\Meta;
use SpotifyWebApiLib\Models\SectionObject;
use SpotifyWebApiLib\Models\SegmentObject;
use SpotifyWebApiLib\Models\TimeIntervalObject;
use SpotifyWebApiLib\Models\Track;

/**
 * Builder for model AudioAnalysisObject
 *
 * @see AudioAnalysisObject
 */
class AudioAnalysisObjectBuilder
{
    /**
     * @var AudioAnalysisObject
     */
    private $instance;

    private function __construct(AudioAnalysisObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Audio Analysis Object Builder object.
     */
    public static function init(): self
    {
        return new self(new AudioAnalysisObject());
    }

    /**
     * Sets meta field.
     *
     * @param Meta|null $value
     */
    public function meta(?Meta $value): self
    {
        $this->instance->setMeta($value);
        return $this;
    }

    /**
     * Sets track field.
     *
     * @param Track|null $value
     */
    public function track(?Track $value): self
    {
        $this->instance->setTrack($value);
        return $this;
    }

    /**
     * Sets bars field.
     *
     * @param TimeIntervalObject[]|null $value
     */
    public function bars(?array $value): self
    {
        $this->instance->setBars($value);
        return $this;
    }

    /**
     * Sets beats field.
     *
     * @param TimeIntervalObject[]|null $value
     */
    public function beats(?array $value): self
    {
        $this->instance->setBeats($value);
        return $this;
    }

    /**
     * Sets sections field.
     *
     * @param SectionObject[]|null $value
     */
    public function sections(?array $value): self
    {
        $this->instance->setSections($value);
        return $this;
    }

    /**
     * Sets segments field.
     *
     * @param SegmentObject[]|null $value
     */
    public function segments(?array $value): self
    {
        $this->instance->setSegments($value);
        return $this;
    }

    /**
     * Sets tatums field.
     *
     * @param TimeIntervalObject[]|null $value
     */
    public function tatums(?array $value): self
    {
        $this->instance->setTatums($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Audio Analysis Object object.
     */
    public function build(): AudioAnalysisObject
    {
        return CoreHelper::clone($this->instance);
    }
}
