<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\AudioFeaturesObject;

/**
 * Builder for model AudioFeaturesObject
 *
 * @see AudioFeaturesObject
 */
class AudioFeaturesObjectBuilder
{
    /**
     * @var AudioFeaturesObject
     */
    private $instance;

    private function __construct(AudioFeaturesObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Audio Features Object Builder object.
     */
    public static function init(): self
    {
        return new self(new AudioFeaturesObject());
    }

    /**
     * Sets acousticness field.
     *
     * @param float|null $value
     */
    public function acousticness(?float $value): self
    {
        $this->instance->setAcousticness($value);
        return $this;
    }

    /**
     * Sets analysis url field.
     *
     * @param string|null $value
     */
    public function analysisUrl(?string $value): self
    {
        $this->instance->setAnalysisUrl($value);
        return $this;
    }

    /**
     * Sets danceability field.
     *
     * @param float|null $value
     */
    public function danceability(?float $value): self
    {
        $this->instance->setDanceability($value);
        return $this;
    }

    /**
     * Sets duration ms field.
     *
     * @param int|null $value
     */
    public function durationMs(?int $value): self
    {
        $this->instance->setDurationMs($value);
        return $this;
    }

    /**
     * Sets energy field.
     *
     * @param float|null $value
     */
    public function energy(?float $value): self
    {
        $this->instance->setEnergy($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets instrumentalness field.
     *
     * @param float|null $value
     */
    public function instrumentalness(?float $value): self
    {
        $this->instance->setInstrumentalness($value);
        return $this;
    }

    /**
     * Sets key field.
     *
     * @param int|null $value
     */
    public function key(?int $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Sets liveness field.
     *
     * @param float|null $value
     */
    public function liveness(?float $value): self
    {
        $this->instance->setLiveness($value);
        return $this;
    }

    /**
     * Sets loudness field.
     *
     * @param float|null $value
     */
    public function loudness(?float $value): self
    {
        $this->instance->setLoudness($value);
        return $this;
    }

    /**
     * Sets mode field.
     *
     * @param int|null $value
     */
    public function mode(?int $value): self
    {
        $this->instance->setMode($value);
        return $this;
    }

    /**
     * Sets speechiness field.
     *
     * @param float|null $value
     */
    public function speechiness(?float $value): self
    {
        $this->instance->setSpeechiness($value);
        return $this;
    }

    /**
     * Sets tempo field.
     *
     * @param float|null $value
     */
    public function tempo(?float $value): self
    {
        $this->instance->setTempo($value);
        return $this;
    }

    /**
     * Sets time signature field.
     *
     * @param int|null $value
     */
    public function timeSignature(?int $value): self
    {
        $this->instance->setTimeSignature($value);
        return $this;
    }

    /**
     * Sets track href field.
     *
     * @param string|null $value
     */
    public function trackHref(?string $value): self
    {
        $this->instance->setTrackHref($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets uri field.
     *
     * @param string|null $value
     */
    public function uri(?string $value): self
    {
        $this->instance->setUri($value);
        return $this;
    }

    /**
     * Sets valence field.
     *
     * @param float|null $value
     */
    public function valence(?float $value): self
    {
        $this->instance->setValence($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Audio Features Object object.
     */
    public function build(): AudioFeaturesObject
    {
        return CoreHelper::clone($this->instance);
    }
}
