<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\AudiobookObject;
use SpotifyWebApiLib\Models\AuthorObject;
use SpotifyWebApiLib\Models\CopyrightObject;
use SpotifyWebApiLib\Models\ExternalUrlObject;
use SpotifyWebApiLib\Models\ImageObject;
use SpotifyWebApiLib\Models\NarratorObject;
use SpotifyWebApiLib\Models\PagingSimplifiedChapterObject;

/**
 * Builder for model AudiobookObject
 *
 * @see AudiobookObject
 */
class AudiobookObjectBuilder
{
    /**
     * @var AudiobookObject
     */
    private $instance;

    private function __construct(AudiobookObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Audiobook Object Builder object.
     *
     * @param AuthorObject[] $authors
     * @param string[] $availableMarkets
     * @param CopyrightObject[] $copyrights
     * @param string $description
     * @param string $htmlDescription
     * @param bool $explicit
     * @param ExternalUrlObject $externalUrls
     * @param string $href
     * @param string $id
     * @param ImageObject[] $images
     * @param string[] $languages
     * @param string $mediaType
     * @param string $name
     * @param NarratorObject[] $narrators
     * @param string $publisher
     * @param string $type
     * @param string $uri
     * @param int $totalChapters
     * @param PagingSimplifiedChapterObject $chapters
     */
    public static function init(
        array $authors,
        array $availableMarkets,
        array $copyrights,
        string $description,
        string $htmlDescription,
        bool $explicit,
        ExternalUrlObject $externalUrls,
        string $href,
        string $id,
        array $images,
        array $languages,
        string $mediaType,
        string $name,
        array $narrators,
        string $publisher,
        string $type,
        string $uri,
        int $totalChapters,
        PagingSimplifiedChapterObject $chapters
    ): self {
        return new self(new AudiobookObject(
            $authors,
            $availableMarkets,
            $copyrights,
            $description,
            $htmlDescription,
            $explicit,
            $externalUrls,
            $href,
            $id,
            $images,
            $languages,
            $mediaType,
            $name,
            $narrators,
            $publisher,
            $type,
            $uri,
            $totalChapters,
            $chapters
        ));
    }

    /**
     * Sets edition field.
     *
     * @param string|null $value
     */
    public function edition(?string $value): self
    {
        $this->instance->setEdition($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Audiobook Object object.
     */
    public function build(): AudiobookObject
    {
        return CoreHelper::clone($this->instance);
    }
}
