<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\CategoryObject;
use SpotifyWebApiLib\Models\ImageObject;

/**
 * Builder for model CategoryObject
 *
 * @see CategoryObject
 */
class CategoryObjectBuilder
{
    /**
     * @var CategoryObject
     */
    private $instance;

    private function __construct(CategoryObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Category Object Builder object.
     *
     * @param string $href
     * @param ImageObject[] $icons
     * @param string $id
     * @param string $name
     */
    public static function init(string $href, array $icons, string $id, string $name): self
    {
        return new self(new CategoryObject($href, $icons, $id, $name));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Category Object object.
     */
    public function build(): CategoryObject
    {
        return CoreHelper::clone($this->instance);
    }
}
