<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ChapterBase;
use SpotifyWebApiLib\Models\ChapterRestrictionObject;
use SpotifyWebApiLib\Models\ExternalUrlObject;
use SpotifyWebApiLib\Models\ImageObject;
use SpotifyWebApiLib\Models\ResumePointObject;

/**
 * Builder for model ChapterBase
 *
 * @see ChapterBase
 */
class ChapterBaseBuilder
{
    /**
     * @var ChapterBase
     */
    private $instance;

    private function __construct(ChapterBase $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Chapter Base Builder object.
     *
     * @param int $chapterNumber
     * @param string $description
     * @param string $htmlDescription
     * @param int $durationMs
     * @param bool $explicit
     * @param ExternalUrlObject $externalUrls
     * @param string $href
     * @param string $id
     * @param ImageObject[] $images
     * @param bool $isPlayable
     * @param string[] $languages
     * @param string $name
     * @param string $releaseDate
     * @param string $releaseDatePrecision
     * @param string $type
     * @param string $uri
     */
    public static function init(
        int $chapterNumber,
        string $description,
        string $htmlDescription,
        int $durationMs,
        bool $explicit,
        ExternalUrlObject $externalUrls,
        string $href,
        string $id,
        array $images,
        bool $isPlayable,
        array $languages,
        string $name,
        string $releaseDate,
        string $releaseDatePrecision,
        string $type,
        string $uri
    ): self {
        return new self(new ChapterBase(
            $chapterNumber,
            $description,
            $htmlDescription,
            $durationMs,
            $explicit,
            $externalUrls,
            $href,
            $id,
            $images,
            $isPlayable,
            $languages,
            $name,
            $releaseDate,
            $releaseDatePrecision,
            $type,
            $uri
        ));
    }

    /**
     * Sets audio preview url field.
     *
     * @param string|null $value
     */
    public function audioPreviewUrl(?string $value): self
    {
        $this->instance->setAudioPreviewUrl($value);
        return $this;
    }

    /**
     * Sets available markets field.
     *
     * @param string[]|null $value
     */
    public function availableMarkets(?array $value): self
    {
        $this->instance->setAvailableMarkets($value);
        return $this;
    }

    /**
     * Sets resume point field.
     *
     * @param ResumePointObject|null $value
     */
    public function resumePoint(?ResumePointObject $value): self
    {
        $this->instance->setResumePoint($value);
        return $this;
    }

    /**
     * Sets restrictions field.
     *
     * @param ChapterRestrictionObject|null $value
     */
    public function restrictions(?ChapterRestrictionObject $value): self
    {
        $this->instance->setRestrictions($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Chapter Base object.
     */
    public function build(): ChapterBase
    {
        return CoreHelper::clone($this->instance);
    }
}
