<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\CopyrightObject;

/**
 * Builder for model CopyrightObject
 *
 * @see CopyrightObject
 */
class CopyrightObjectBuilder
{
    /**
     * @var CopyrightObject
     */
    private $instance;

    private function __construct(CopyrightObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Copyright Object Builder object.
     */
    public static function init(): self
    {
        return new self(new CopyrightObject());
    }

    /**
     * Sets text field.
     *
     * @param string|null $value
     */
    public function text(?string $value): self
    {
        $this->instance->setText($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Copyright Object object.
     */
    public function build(): CopyrightObject
    {
        return CoreHelper::clone($this->instance);
    }
}
