<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ContextObject;
use SpotifyWebApiLib\Models\CurrentlyPlayingObject;
use SpotifyWebApiLib\Models\DisallowsObject;
use SpotifyWebApiLib\Models\EpisodeObject;
use SpotifyWebApiLib\Models\TrackObject;

/**
 * Builder for model CurrentlyPlayingObject
 *
 * @see CurrentlyPlayingObject
 */
class CurrentlyPlayingObjectBuilder
{
    /**
     * @var CurrentlyPlayingObject
     */
    private $instance;

    private function __construct(CurrentlyPlayingObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Currently Playing Object Builder object.
     */
    public static function init(): self
    {
        return new self(new CurrentlyPlayingObject());
    }

    /**
     * Sets context field.
     *
     * @param ContextObject|null $value
     */
    public function context(?ContextObject $value): self
    {
        $this->instance->setContext($value);
        return $this;
    }

    /**
     * Sets timestamp field.
     *
     * @param int|null $value
     */
    public function timestamp(?int $value): self
    {
        $this->instance->setTimestamp($value);
        return $this;
    }

    /**
     * Sets progress ms field.
     *
     * @param int|null $value
     */
    public function progressMs(?int $value): self
    {
        $this->instance->setProgressMs($value);
        return $this;
    }

    /**
     * Sets is playing field.
     *
     * @param bool|null $value
     */
    public function isPlaying(?bool $value): self
    {
        $this->instance->setIsPlaying($value);
        return $this;
    }

    /**
     * Sets item field.
     *
     * @param TrackObject|EpisodeObject|null $value
     */
    public function item($value): self
    {
        $this->instance->setItem($value);
        return $this;
    }

    /**
     * Sets currently playing type field.
     *
     * @param string|null $value
     */
    public function currentlyPlayingType(?string $value): self
    {
        $this->instance->setCurrentlyPlayingType($value);
        return $this;
    }

    /**
     * Sets actions field.
     *
     * @param DisallowsObject|null $value
     */
    public function actions(?DisallowsObject $value): self
    {
        $this->instance->setActions($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Currently Playing Object object.
     */
    public function build(): CurrentlyPlayingObject
    {
        return CoreHelper::clone($this->instance);
    }
}
