<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\CursorObject;

/**
 * Builder for model CursorObject
 *
 * @see CursorObject
 */
class CursorObjectBuilder
{
    /**
     * @var CursorObject
     */
    private $instance;

    private function __construct(CursorObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cursor Object Builder object.
     */
    public static function init(): self
    {
        return new self(new CursorObject());
    }

    /**
     * Sets after field.
     *
     * @param string|null $value
     */
    public function after(?string $value): self
    {
        $this->instance->setAfter($value);
        return $this;
    }

    /**
     * Sets before field.
     *
     * @param string|null $value
     */
    public function before(?string $value): self
    {
        $this->instance->setBefore($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Cursor Object object.
     */
    public function build(): CursorObject
    {
        return CoreHelper::clone($this->instance);
    }
}
