<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\CursorPagedArtists;
use SpotifyWebApiLib\Models\CursorPagingSimplifiedArtistObject;

/**
 * Builder for model CursorPagedArtists
 *
 * @see CursorPagedArtists
 */
class CursorPagedArtistsBuilder
{
    /**
     * @var CursorPagedArtists
     */
    private $instance;

    private function __construct(CursorPagedArtists $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cursor Paged Artists Builder object.
     *
     * @param CursorPagingSimplifiedArtistObject $artists
     */
    public static function init(CursorPagingSimplifiedArtistObject $artists): self
    {
        return new self(new CursorPagedArtists($artists));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Cursor Paged Artists object.
     */
    public function build(): CursorPagedArtists
    {
        return CoreHelper::clone($this->instance);
    }
}
