<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\DeviceObject;

/**
 * Builder for model DeviceObject
 *
 * @see DeviceObject
 */
class DeviceObjectBuilder
{
    /**
     * @var DeviceObject
     */
    private $instance;

    private function __construct(DeviceObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Device Object Builder object.
     */
    public static function init(): self
    {
        return new self(new DeviceObject());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Unsets id field.
     */
    public function unsetId(): self
    {
        $this->instance->unsetId();
        return $this;
    }

    /**
     * Sets is active field.
     *
     * @param bool|null $value
     */
    public function isActive(?bool $value): self
    {
        $this->instance->setIsActive($value);
        return $this;
    }

    /**
     * Sets is private session field.
     *
     * @param bool|null $value
     */
    public function isPrivateSession(?bool $value): self
    {
        $this->instance->setIsPrivateSession($value);
        return $this;
    }

    /**
     * Sets is restricted field.
     *
     * @param bool|null $value
     */
    public function isRestricted(?bool $value): self
    {
        $this->instance->setIsRestricted($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets volume percent field.
     *
     * @param int|null $value
     */
    public function volumePercent(?int $value): self
    {
        $this->instance->setVolumePercent($value);
        return $this;
    }

    /**
     * Unsets volume percent field.
     */
    public function unsetVolumePercent(): self
    {
        $this->instance->unsetVolumePercent();
        return $this;
    }

    /**
     * Sets supports volume field.
     *
     * @param bool|null $value
     */
    public function supportsVolume(?bool $value): self
    {
        $this->instance->setSupportsVolume($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Device Object object.
     */
    public function build(): DeviceObject
    {
        return CoreHelper::clone($this->instance);
    }
}
