<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\EpisodeObject;
use SpotifyWebApiLib\Models\ExternalUrlObject;
use SpotifyWebApiLib\Models\ImageObject;
use SpotifyWebApiLib\Models\ResumePointObject;
use SpotifyWebApiLib\Models\ShowBase;
use SpotifyWebApiLib\Models\TrackRestrictionObject;

/**
 * Builder for model EpisodeObject
 *
 * @see EpisodeObject
 */
class EpisodeObjectBuilder
{
    /**
     * @var EpisodeObject
     */
    private $instance;

    private function __construct(EpisodeObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Episode Object Builder object.
     *
     * @param string $description
     * @param string $htmlDescription
     * @param int $durationMs
     * @param bool $explicit
     * @param ExternalUrlObject $externalUrls
     * @param string $href
     * @param string $id
     * @param ImageObject[] $images
     * @param bool $isExternallyHosted
     * @param bool $isPlayable
     * @param string[] $languages
     * @param string $name
     * @param string $releaseDate
     * @param string $releaseDatePrecision
     * @param string $type
     * @param string $uri
     * @param ShowBase $show
     */
    public static function init(
        string $description,
        string $htmlDescription,
        int $durationMs,
        bool $explicit,
        ExternalUrlObject $externalUrls,
        string $href,
        string $id,
        array $images,
        bool $isExternallyHosted,
        bool $isPlayable,
        array $languages,
        string $name,
        string $releaseDate,
        string $releaseDatePrecision,
        string $type,
        string $uri,
        ShowBase $show
    ): self {
        return new self(new EpisodeObject(
            $description,
            $htmlDescription,
            $durationMs,
            $explicit,
            $externalUrls,
            $href,
            $id,
            $images,
            $isExternallyHosted,
            $isPlayable,
            $languages,
            $name,
            $releaseDate,
            $releaseDatePrecision,
            $type,
            $uri,
            $show
        ));
    }

    /**
     * Sets audio preview url field.
     *
     * @param string|null $value
     */
    public function audioPreviewUrl(?string $value): self
    {
        $this->instance->setAudioPreviewUrl($value);
        return $this;
    }

    /**
     * Sets language field.
     *
     * @param string|null $value
     */
    public function language(?string $value): self
    {
        $this->instance->setLanguage($value);
        return $this;
    }

    /**
     * Sets resume point field.
     *
     * @param ResumePointObject|null $value
     */
    public function resumePoint(?ResumePointObject $value): self
    {
        $this->instance->setResumePoint($value);
        return $this;
    }

    /**
     * Sets restrictions field.
     *
     * @param TrackRestrictionObject|null $value
     */
    public function restrictions(?TrackRestrictionObject $value): self
    {
        $this->instance->setRestrictions($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Episode Object object.
     */
    public function build(): EpisodeObject
    {
        return CoreHelper::clone($this->instance);
    }
}
