<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ErrorObject;

/**
 * Builder for model ErrorObject
 *
 * @see ErrorObject
 */
class ErrorObjectBuilder
{
    /**
     * @var ErrorObject
     */
    private $instance;

    private function __construct(ErrorObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Object Builder object.
     *
     * @param int $status
     * @param string $message
     */
    public static function init(int $status, string $message): self
    {
        return new self(new ErrorObject($status, $message));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Error Object object.
     */
    public function build(): ErrorObject
    {
        return CoreHelper::clone($this->instance);
    }
}
