<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ExplicitContentSettingsObject;

/**
 * Builder for model ExplicitContentSettingsObject
 *
 * @see ExplicitContentSettingsObject
 */
class ExplicitContentSettingsObjectBuilder
{
    /**
     * @var ExplicitContentSettingsObject
     */
    private $instance;

    private function __construct(ExplicitContentSettingsObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Explicit Content Settings Object Builder object.
     */
    public static function init(): self
    {
        return new self(new ExplicitContentSettingsObject());
    }

    /**
     * Sets filter enabled field.
     *
     * @param bool|null $value
     */
    public function filterEnabled(?bool $value): self
    {
        $this->instance->setFilterEnabled($value);
        return $this;
    }

    /**
     * Sets filter locked field.
     *
     * @param bool|null $value
     */
    public function filterLocked(?bool $value): self
    {
        $this->instance->setFilterLocked($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Explicit Content Settings Object object.
     */
    public function build(): ExplicitContentSettingsObject
    {
        return CoreHelper::clone($this->instance);
    }
}
