<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ExternalIdObject;

/**
 * Builder for model ExternalIdObject
 *
 * @see ExternalIdObject
 */
class ExternalIdObjectBuilder
{
    /**
     * @var ExternalIdObject
     */
    private $instance;

    private function __construct(ExternalIdObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new External Id Object Builder object.
     */
    public static function init(): self
    {
        return new self(new ExternalIdObject());
    }

    /**
     * Sets isrc field.
     *
     * @param string|null $value
     */
    public function isrc(?string $value): self
    {
        $this->instance->setIsrc($value);
        return $this;
    }

    /**
     * Sets ean field.
     *
     * @param string|null $value
     */
    public function ean(?string $value): self
    {
        $this->instance->setEan($value);
        return $this;
    }

    /**
     * Sets upc field.
     *
     * @param string|null $value
     */
    public function upc(?string $value): self
    {
        $this->instance->setUpc($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new External Id Object object.
     */
    public function build(): ExternalIdObject
    {
        return CoreHelper::clone($this->instance);
    }
}
