<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\FollowArtistsOrUsersRequest;

/**
 * Builder for model FollowArtistsOrUsersRequest
 *
 * @see FollowArtistsOrUsersRequest
 */
class FollowArtistsOrUsersRequestBuilder
{
    /**
     * @var FollowArtistsOrUsersRequest
     */
    private $instance;

    private function __construct(FollowArtistsOrUsersRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Follow Artists Or Users Request Builder object.
     *
     * @param string[] $ids
     */
    public static function init(array $ids): self
    {
        return new self(new FollowArtistsOrUsersRequest($ids));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Follow Artists Or Users Request object.
     */
    public function build(): FollowArtistsOrUsersRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
