<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ImageObject;

/**
 * Builder for model ImageObject
 *
 * @see ImageObject
 */
class ImageObjectBuilder
{
    /**
     * @var ImageObject
     */
    private $instance;

    private function __construct(ImageObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Image Object Builder object.
     *
     * @param string $url
     */
    public static function init(string $url): self
    {
        return new self(new ImageObject($url));
    }

    /**
     * Sets height field.
     *
     * @param int|null $value
     */
    public function height(?int $value): self
    {
        $this->instance->setHeight($value);
        return $this;
    }

    /**
     * Sets width field.
     *
     * @param int|null $value
     */
    public function width(?int $value): self
    {
        $this->instance->setWidth($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Image Object object.
     */
    public function build(): ImageObject
    {
        return CoreHelper::clone($this->instance);
    }
}
