<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ManySimplifiedShows;
use SpotifyWebApiLib\Models\ShowBase;

/**
 * Builder for model ManySimplifiedShows
 *
 * @see ManySimplifiedShows
 */
class ManySimplifiedShowsBuilder
{
    /**
     * @var ManySimplifiedShows
     */
    private $instance;

    private function __construct(ManySimplifiedShows $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Many Simplified Shows Builder object.
     *
     * @param ShowBase[] $shows
     */
    public static function init(array $shows): self
    {
        return new self(new ManySimplifiedShows($shows));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Many Simplified Shows object.
     */
    public function build(): ManySimplifiedShows
    {
        return CoreHelper::clone($this->instance);
    }
}
