<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\AudioFeaturesObject;
use SpotifyWebApiLib\Models\ManyAudioFeatures;

/**
 * Builder for model ManyAudioFeatures
 *
 * @see ManyAudioFeatures
 */
class ManyAudioFeaturesBuilder
{
    /**
     * @var ManyAudioFeatures
     */
    private $instance;

    private function __construct(ManyAudioFeatures $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Many Audio Features Builder object.
     *
     * @param AudioFeaturesObject[] $audioFeatures
     */
    public static function init(array $audioFeatures): self
    {
        return new self(new ManyAudioFeatures($audioFeatures));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Many Audio Features object.
     */
    public function build(): ManyAudioFeatures
    {
        return CoreHelper::clone($this->instance);
    }
}
