<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ChapterObject;
use SpotifyWebApiLib\Models\ManyChapters;

/**
 * Builder for model ManyChapters
 *
 * @see ManyChapters
 */
class ManyChaptersBuilder
{
    /**
     * @var ManyChapters
     */
    private $instance;

    private function __construct(ManyChapters $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Many Chapters Builder object.
     *
     * @param ChapterObject[] $chapters
     */
    public static function init(array $chapters): self
    {
        return new self(new ManyChapters($chapters));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Many Chapters object.
     */
    public function build(): ManyChapters
    {
        return CoreHelper::clone($this->instance);
    }
}
