<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\AudiobookObject;
use SpotifyWebApiLib\Models\ManyAudiobooks;

/**
 * Builder for model ManyAudiobooks
 *
 * @see ManyAudiobooks
 */
class ManyAudiobooksBuilder
{
    /**
     * @var ManyAudiobooks
     */
    private $instance;

    private function __construct(ManyAudiobooks $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Many Audiobooks Builder object.
     *
     * @param AudiobookObject[] $audiobooks
     */
    public static function init(array $audiobooks): self
    {
        return new self(new ManyAudiobooks($audiobooks));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Many Audiobooks object.
     */
    public function build(): ManyAudiobooks
    {
        return CoreHelper::clone($this->instance);
    }
}
