<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\AlbumObject;
use SpotifyWebApiLib\Models\ManyAlbums;

/**
 * Builder for model ManyAlbums
 *
 * @see ManyAlbums
 */
class ManyAlbumsBuilder
{
    /**
     * @var ManyAlbums
     */
    private $instance;

    private function __construct(ManyAlbums $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Many Albums Builder object.
     *
     * @param AlbumObject[] $albums
     */
    public static function init(array $albums): self
    {
        return new self(new ManyAlbums($albums));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Many Albums object.
     */
    public function build(): ManyAlbums
    {
        return CoreHelper::clone($this->instance);
    }
}
