<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ManyGenres;

/**
 * Builder for model ManyGenres
 *
 * @see ManyGenres
 */
class ManyGenresBuilder
{
    /**
     * @var ManyGenres
     */
    private $instance;

    private function __construct(ManyGenres $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Many Genres Builder object.
     *
     * @param string[] $genres
     */
    public static function init(array $genres): self
    {
        return new self(new ManyGenres($genres));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Many Genres object.
     */
    public function build(): ManyGenres
    {
        return CoreHelper::clone($this->instance);
    }
}
