<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ArtistObject;
use SpotifyWebApiLib\Models\ManyArtists;

/**
 * Builder for model ManyArtists
 *
 * @see ManyArtists
 */
class ManyArtistsBuilder
{
    /**
     * @var ManyArtists
     */
    private $instance;

    private function __construct(ManyArtists $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Many Artists Builder object.
     *
     * @param ArtistObject[] $artists
     */
    public static function init(array $artists): self
    {
        return new self(new ManyArtists($artists));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Many Artists object.
     */
    public function build(): ManyArtists
    {
        return CoreHelper::clone($this->instance);
    }
}
