<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\EpisodeObject;
use SpotifyWebApiLib\Models\ManyEpisodes;

/**
 * Builder for model ManyEpisodes
 *
 * @see ManyEpisodes
 */
class ManyEpisodesBuilder
{
    /**
     * @var ManyEpisodes
     */
    private $instance;

    private function __construct(ManyEpisodes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Many Episodes Builder object.
     *
     * @param EpisodeObject[] $episodes
     */
    public static function init(array $episodes): self
    {
        return new self(new ManyEpisodes($episodes));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Many Episodes object.
     */
    public function build(): ManyEpisodes
    {
        return CoreHelper::clone($this->instance);
    }
}
