<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ManyTracks;
use SpotifyWebApiLib\Models\TrackObject;

/**
 * Builder for model ManyTracks
 *
 * @see ManyTracks
 */
class ManyTracksBuilder
{
    /**
     * @var ManyTracks
     */
    private $instance;

    private function __construct(ManyTracks $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Many Tracks Builder object.
     *
     * @param TrackObject[] $tracks
     */
    public static function init(array $tracks): self
    {
        return new self(new ManyTracks($tracks));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Many Tracks object.
     */
    public function build(): ManyTracks
    {
        return CoreHelper::clone($this->instance);
    }
}
