<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\Markets;

/**
 * Builder for model Markets
 *
 * @see Markets
 */
class MarketsBuilder
{
    /**
     * @var Markets
     */
    private $instance;

    private function __construct(Markets $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Markets Builder object.
     */
    public static function init(): self
    {
        return new self(new Markets());
    }

    /**
     * Sets markets field.
     *
     * @param string[]|null $value
     */
    public function markets(?array $value): self
    {
        $this->instance->setMarkets($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Markets object.
     */
    public function build(): Markets
    {
        return CoreHelper::clone($this->instance);
    }
}
