<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\Meta;

/**
 * Builder for model Meta
 *
 * @see Meta
 */
class MetaBuilder
{
    /**
     * @var Meta
     */
    private $instance;

    private function __construct(Meta $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Meta Builder object.
     */
    public static function init(): self
    {
        return new self(new Meta());
    }

    /**
     * Sets analyzer version field.
     *
     * @param string|null $value
     */
    public function analyzerVersion(?string $value): self
    {
        $this->instance->setAnalyzerVersion($value);
        return $this;
    }

    /**
     * Sets platform field.
     *
     * @param string|null $value
     */
    public function platform(?string $value): self
    {
        $this->instance->setPlatform($value);
        return $this;
    }

    /**
     * Sets detailed status field.
     *
     * @param string|null $value
     */
    public function detailedStatus(?string $value): self
    {
        $this->instance->setDetailedStatus($value);
        return $this;
    }

    /**
     * Sets status code field.
     *
     * @param int|null $value
     */
    public function statusCode(?int $value): self
    {
        $this->instance->setStatusCode($value);
        return $this;
    }

    /**
     * Sets timestamp field.
     *
     * @param int|null $value
     */
    public function timestamp(?int $value): self
    {
        $this->instance->setTimestamp($value);
        return $this;
    }

    /**
     * Sets analysis time field.
     *
     * @param float|null $value
     */
    public function analysisTime(?float $value): self
    {
        $this->instance->setAnalysisTime($value);
        return $this;
    }

    /**
     * Sets input process field.
     *
     * @param string|null $value
     */
    public function inputProcess(?string $value): self
    {
        $this->instance->setInputProcess($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Meta object.
     */
    public function build(): Meta
    {
        return CoreHelper::clone($this->instance);
    }
}
