<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\NarratorObject;

/**
 * Builder for model NarratorObject
 *
 * @see NarratorObject
 */
class NarratorObjectBuilder
{
    /**
     * @var NarratorObject
     */
    private $instance;

    private function __construct(NarratorObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Narrator Object Builder object.
     */
    public static function init(): self
    {
        return new self(new NarratorObject());
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Narrator Object object.
     */
    public function build(): NarratorObject
    {
        return CoreHelper::clone($this->instance);
    }
}
