<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\Categories;
use SpotifyWebApiLib\Models\PagedCategories;

/**
 * Builder for model PagedCategories
 *
 * @see PagedCategories
 */
class PagedCategoriesBuilder
{
    /**
     * @var PagedCategories
     */
    private $instance;

    private function __construct(PagedCategories $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Paged Categories Builder object.
     *
     * @param Categories $categories
     */
    public static function init(Categories $categories): self
    {
        return new self(new PagedCategories($categories));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Paged Categories object.
     */
    public function build(): PagedCategories
    {
        return CoreHelper::clone($this->instance);
    }
}
