<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\PagedAlbums;
use SpotifyWebApiLib\Models\PagingSimplifiedAlbumObject;

/**
 * Builder for model PagedAlbums
 *
 * @see PagedAlbums
 */
class PagedAlbumsBuilder
{
    /**
     * @var PagedAlbums
     */
    private $instance;

    private function __construct(PagedAlbums $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Paged Albums Builder object.
     *
     * @param PagingSimplifiedAlbumObject $albums
     */
    public static function init(PagingSimplifiedAlbumObject $albums): self
    {
        return new self(new PagedAlbums($albums));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Paged Albums object.
     */
    public function build(): PagedAlbums
    {
        return CoreHelper::clone($this->instance);
    }
}
