<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\PagingSavedEpisodeObject;
use SpotifyWebApiLib\Models\SavedEpisodeObject;

/**
 * Builder for model PagingSavedEpisodeObject
 *
 * @see PagingSavedEpisodeObject
 */
class PagingSavedEpisodeObjectBuilder
{
    /**
     * @var PagingSavedEpisodeObject
     */
    private $instance;

    private function __construct(PagingSavedEpisodeObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Paging Saved Episode Object Builder object.
     *
     * @param string $href
     * @param int $limit
     * @param int $offset
     * @param int $total
     * @param SavedEpisodeObject[] $items
     */
    public static function init(string $href, int $limit, int $offset, int $total, array $items): self
    {
        return new self(new PagingSavedEpisodeObject($href, $limit, $offset, $total, $items));
    }

    /**
     * Sets next field.
     *
     * @param string|null $value
     */
    public function next(?string $value): self
    {
        $this->instance->setNext($value);
        return $this;
    }

    /**
     * Sets previous field.
     *
     * @param string|null $value
     */
    public function previous(?string $value): self
    {
        $this->instance->setPrevious($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Paging Saved Episode Object object.
     */
    public function build(): PagingSavedEpisodeObject
    {
        return CoreHelper::clone($this->instance);
    }
}
