<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ExternalUrlObject;
use SpotifyWebApiLib\Models\FollowersObject;
use SpotifyWebApiLib\Models\ImageObject;
use SpotifyWebApiLib\Models\PagingPlaylistTrackObject;
use SpotifyWebApiLib\Models\PlaylistObject;
use SpotifyWebApiLib\Models\PlaylistOwnerObject;

/**
 * Builder for model PlaylistObject
 *
 * @see PlaylistObject
 */
class PlaylistObjectBuilder
{
    /**
     * @var PlaylistObject
     */
    private $instance;

    private function __construct(PlaylistObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Playlist Object Builder object.
     */
    public static function init(): self
    {
        return new self(new PlaylistObject());
    }

    /**
     * Sets collaborative field.
     *
     * @param bool|null $value
     */
    public function collaborative(?bool $value): self
    {
        $this->instance->setCollaborative($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Unsets description field.
     */
    public function unsetDescription(): self
    {
        $this->instance->unsetDescription();
        return $this;
    }

    /**
     * Sets external urls field.
     *
     * @param ExternalUrlObject|null $value
     */
    public function externalUrls(?ExternalUrlObject $value): self
    {
        $this->instance->setExternalUrls($value);
        return $this;
    }

    /**
     * Sets followers field.
     *
     * @param FollowersObject|null $value
     */
    public function followers(?FollowersObject $value): self
    {
        $this->instance->setFollowers($value);
        return $this;
    }

    /**
     * Sets href field.
     *
     * @param string|null $value
     */
    public function href(?string $value): self
    {
        $this->instance->setHref($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets images field.
     *
     * @param ImageObject[]|null $value
     */
    public function images(?array $value): self
    {
        $this->instance->setImages($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets owner field.
     *
     * @param PlaylistOwnerObject|null $value
     */
    public function owner(?PlaylistOwnerObject $value): self
    {
        $this->instance->setOwner($value);
        return $this;
    }

    /**
     * Sets public field.
     *
     * @param bool|null $value
     */
    public function public(?bool $value): self
    {
        $this->instance->setPublic($value);
        return $this;
    }

    /**
     * Sets snapshot id field.
     *
     * @param string|null $value
     */
    public function snapshotId(?string $value): self
    {
        $this->instance->setSnapshotId($value);
        return $this;
    }

    /**
     * Sets tracks field.
     *
     * @param PagingPlaylistTrackObject|null $value
     */
    public function tracks(?PagingPlaylistTrackObject $value): self
    {
        $this->instance->setTracks($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets uri field.
     *
     * @param string|null $value
     */
    public function uri(?string $value): self
    {
        $this->instance->setUri($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Playlist Object object.
     */
    public function build(): PlaylistObject
    {
        return CoreHelper::clone($this->instance);
    }
}
