<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\EpisodeObject;
use SpotifyWebApiLib\Models\PlaylistTrackObject;
use SpotifyWebApiLib\Models\PlaylistUserObject;
use SpotifyWebApiLib\Models\TrackObject;

/**
 * Builder for model PlaylistTrackObject
 *
 * @see PlaylistTrackObject
 */
class PlaylistTrackObjectBuilder
{
    /**
     * @var PlaylistTrackObject
     */
    private $instance;

    private function __construct(PlaylistTrackObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Playlist Track Object Builder object.
     */
    public static function init(): self
    {
        return new self(new PlaylistTrackObject());
    }

    /**
     * Sets added at field.
     *
     * @param \DateTime|null $value
     */
    public function addedAt(?\DateTime $value): self
    {
        $this->instance->setAddedAt($value);
        return $this;
    }

    /**
     * Sets added by field.
     *
     * @param PlaylistUserObject|null $value
     */
    public function addedBy(?PlaylistUserObject $value): self
    {
        $this->instance->setAddedBy($value);
        return $this;
    }

    /**
     * Sets is local field.
     *
     * @param bool|null $value
     */
    public function isLocal(?bool $value): self
    {
        $this->instance->setIsLocal($value);
        return $this;
    }

    /**
     * Sets track field.
     *
     * @param TrackObject|EpisodeObject|null $value
     */
    public function track($value): self
    {
        $this->instance->setTrack($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Playlist Track Object object.
     */
    public function build(): PlaylistTrackObject
    {
        return CoreHelper::clone($this->instance);
    }
}
