<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\PlaylistTracksRefObject;

/**
 * Builder for model PlaylistTracksRefObject
 *
 * @see PlaylistTracksRefObject
 */
class PlaylistTracksRefObjectBuilder
{
    /**
     * @var PlaylistTracksRefObject
     */
    private $instance;

    private function __construct(PlaylistTracksRefObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Playlist Tracks Ref Object Builder object.
     */
    public static function init(): self
    {
        return new self(new PlaylistTracksRefObject());
    }

    /**
     * Sets href field.
     *
     * @param string|null $value
     */
    public function href(?string $value): self
    {
        $this->instance->setHref($value);
        return $this;
    }

    /**
     * Sets total field.
     *
     * @param int|null $value
     */
    public function total(?int $value): self
    {
        $this->instance->setTotal($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Playlist Tracks Ref Object object.
     */
    public function build(): PlaylistTracksRefObject
    {
        return CoreHelper::clone($this->instance);
    }
}
