<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ContextObject;
use SpotifyWebApiLib\Models\PlayHistoryObject;
use SpotifyWebApiLib\Models\TrackObject;

/**
 * Builder for model PlayHistoryObject
 *
 * @see PlayHistoryObject
 */
class PlayHistoryObjectBuilder
{
    /**
     * @var PlayHistoryObject
     */
    private $instance;

    private function __construct(PlayHistoryObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Play History Object Builder object.
     */
    public static function init(): self
    {
        return new self(new PlayHistoryObject());
    }

    /**
     * Sets track field.
     *
     * @param TrackObject|null $value
     */
    public function track(?TrackObject $value): self
    {
        $this->instance->setTrack($value);
        return $this;
    }

    /**
     * Sets played at field.
     *
     * @param \DateTime|null $value
     */
    public function playedAt(?\DateTime $value): self
    {
        $this->instance->setPlayedAt($value);
        return $this;
    }

    /**
     * Sets context field.
     *
     * @param ContextObject|null $value
     */
    public function context(?ContextObject $value): self
    {
        $this->instance->setContext($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Play History Object object.
     */
    public function build(): PlayHistoryObject
    {
        return CoreHelper::clone($this->instance);
    }
}
