<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\PlaylistsTracksRequest;

/**
 * Builder for model PlaylistsTracksRequest
 *
 * @see PlaylistsTracksRequest
 */
class PlaylistsTracksRequestBuilder
{
    /**
     * @var PlaylistsTracksRequest
     */
    private $instance;

    private function __construct(PlaylistsTracksRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Playlists Tracks Request Builder object.
     */
    public static function init(): self
    {
        return new self(new PlaylistsTracksRequest());
    }

    /**
     * Sets uris field.
     *
     * @param string[]|null $value
     */
    public function uris(?array $value): self
    {
        $this->instance->setUris($value);
        return $this;
    }

    /**
     * Sets position field.
     *
     * @param int|null $value
     */
    public function position(?int $value): self
    {
        $this->instance->setPosition($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Playlists Tracks Request object.
     */
    public function build(): PlaylistsTracksRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
