<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ExternalUrlObject;
use SpotifyWebApiLib\Models\FollowersObject;
use SpotifyWebApiLib\Models\PlaylistUserObject;

/**
 * Builder for model PlaylistUserObject
 *
 * @see PlaylistUserObject
 */
class PlaylistUserObjectBuilder
{
    /**
     * @var PlaylistUserObject
     */
    private $instance;

    private function __construct(PlaylistUserObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Playlist User Object Builder object.
     */
    public static function init(): self
    {
        return new self(new PlaylistUserObject());
    }

    /**
     * Sets external urls field.
     *
     * @param ExternalUrlObject|null $value
     */
    public function externalUrls(?ExternalUrlObject $value): self
    {
        $this->instance->setExternalUrls($value);
        return $this;
    }

    /**
     * Sets followers field.
     *
     * @param FollowersObject|null $value
     */
    public function followers(?FollowersObject $value): self
    {
        $this->instance->setFollowers($value);
        return $this;
    }

    /**
     * Sets href field.
     *
     * @param string|null $value
     */
    public function href(?string $value): self
    {
        $this->instance->setHref($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets uri field.
     *
     * @param string|null $value
     */
    public function uri(?string $value): self
    {
        $this->instance->setUri($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Playlist User Object object.
     */
    public function build(): PlaylistUserObject
    {
        return CoreHelper::clone($this->instance);
    }
}
