<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ExplicitContentSettingsObject;
use SpotifyWebApiLib\Models\ExternalUrlObject;
use SpotifyWebApiLib\Models\FollowersObject;
use SpotifyWebApiLib\Models\ImageObject;
use SpotifyWebApiLib\Models\PrivateUserObject;

/**
 * Builder for model PrivateUserObject
 *
 * @see PrivateUserObject
 */
class PrivateUserObjectBuilder
{
    /**
     * @var PrivateUserObject
     */
    private $instance;

    private function __construct(PrivateUserObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Private User Object Builder object.
     */
    public static function init(): self
    {
        return new self(new PrivateUserObject());
    }

    /**
     * Sets country field.
     *
     * @param string|null $value
     */
    public function country(?string $value): self
    {
        $this->instance->setCountry($value);
        return $this;
    }

    /**
     * Sets display name field.
     *
     * @param string|null $value
     */
    public function displayName(?string $value): self
    {
        $this->instance->setDisplayName($value);
        return $this;
    }

    /**
     * Sets email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets explicit content field.
     *
     * @param ExplicitContentSettingsObject|null $value
     */
    public function explicitContent(?ExplicitContentSettingsObject $value): self
    {
        $this->instance->setExplicitContent($value);
        return $this;
    }

    /**
     * Sets external urls field.
     *
     * @param ExternalUrlObject|null $value
     */
    public function externalUrls(?ExternalUrlObject $value): self
    {
        $this->instance->setExternalUrls($value);
        return $this;
    }

    /**
     * Sets followers field.
     *
     * @param FollowersObject|null $value
     */
    public function followers(?FollowersObject $value): self
    {
        $this->instance->setFollowers($value);
        return $this;
    }

    /**
     * Sets href field.
     *
     * @param string|null $value
     */
    public function href(?string $value): self
    {
        $this->instance->setHref($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets images field.
     *
     * @param ImageObject[]|null $value
     */
    public function images(?array $value): self
    {
        $this->instance->setImages($value);
        return $this;
    }

    /**
     * Sets product field.
     *
     * @param string|null $value
     */
    public function product(?string $value): self
    {
        $this->instance->setProduct($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets uri field.
     *
     * @param string|null $value
     */
    public function uri(?string $value): self
    {
        $this->instance->setUri($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Private User Object object.
     */
    public function build(): PrivateUserObject
    {
        return CoreHelper::clone($this->instance);
    }
}
