<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\RecommendationSeedObject;

/**
 * Builder for model RecommendationSeedObject
 *
 * @see RecommendationSeedObject
 */
class RecommendationSeedObjectBuilder
{
    /**
     * @var RecommendationSeedObject
     */
    private $instance;

    private function __construct(RecommendationSeedObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Recommendation Seed Object Builder object.
     */
    public static function init(): self
    {
        return new self(new RecommendationSeedObject());
    }

    /**
     * Sets after Filtering Size field.
     *
     * @param int|null $value
     */
    public function afterFilteringSize(?int $value): self
    {
        $this->instance->setAfterFilteringSize($value);
        return $this;
    }

    /**
     * Sets after Relinking Size field.
     *
     * @param int|null $value
     */
    public function afterRelinkingSize(?int $value): self
    {
        $this->instance->setAfterRelinkingSize($value);
        return $this;
    }

    /**
     * Sets href field.
     *
     * @param string|null $value
     */
    public function href(?string $value): self
    {
        $this->instance->setHref($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets initial Pool Size field.
     *
     * @param int|null $value
     */
    public function initialPoolSize(?int $value): self
    {
        $this->instance->setInitialPoolSize($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Recommendation Seed Object object.
     */
    public function build(): RecommendationSeedObject
    {
        return CoreHelper::clone($this->instance);
    }
}
