<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\RecommendationSeedObject;
use SpotifyWebApiLib\Models\RecommendationsObject;
use SpotifyWebApiLib\Models\TrackObject;

/**
 * Builder for model RecommendationsObject
 *
 * @see RecommendationsObject
 */
class RecommendationsObjectBuilder
{
    /**
     * @var RecommendationsObject
     */
    private $instance;

    private function __construct(RecommendationsObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Recommendations Object Builder object.
     *
     * @param RecommendationSeedObject[] $seeds
     * @param TrackObject[] $tracks
     */
    public static function init(array $seeds, array $tracks): self
    {
        return new self(new RecommendationsObject($seeds, $tracks));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Recommendations Object object.
     */
    public function build(): RecommendationsObject
    {
        return CoreHelper::clone($this->instance);
    }
}
