<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\RemoveShowsRequest;

/**
 * Builder for model RemoveShowsRequest
 *
 * @see RemoveShowsRequest
 */
class RemoveShowsRequestBuilder
{
    /**
     * @var RemoveShowsRequest
     */
    private $instance;

    private function __construct(RemoveShowsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Remove Shows Request Builder object.
     */
    public static function init(): self
    {
        return new self(new RemoveShowsRequest());
    }

    /**
     * Sets ids field.
     *
     * @param string[]|null $value
     */
    public function ids(?array $value): self
    {
        $this->instance->setIds($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Remove Shows Request object.
     */
    public function build(): RemoveShowsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
