<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ResumePointObject;

/**
 * Builder for model ResumePointObject
 *
 * @see ResumePointObject
 */
class ResumePointObjectBuilder
{
    /**
     * @var ResumePointObject
     */
    private $instance;

    private function __construct(ResumePointObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Resume Point Object Builder object.
     */
    public static function init(): self
    {
        return new self(new ResumePointObject());
    }

    /**
     * Sets fully played field.
     *
     * @param bool|null $value
     */
    public function fullyPlayed(?bool $value): self
    {
        $this->instance->setFullyPlayed($value);
        return $this;
    }

    /**
     * Sets resume position ms field.
     *
     * @param int|null $value
     */
    public function resumePositionMs(?int $value): self
    {
        $this->instance->setResumePositionMs($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Resume Point Object object.
     */
    public function build(): ResumePointObject
    {
        return CoreHelper::clone($this->instance);
    }
}
