<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\SaveTracksRequest;

/**
 * Builder for model SaveTracksRequest
 *
 * @see SaveTracksRequest
 */
class SaveTracksRequestBuilder
{
    /**
     * @var SaveTracksRequest
     */
    private $instance;

    private function __construct(SaveTracksRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Save Tracks Request Builder object.
     *
     * @param string[] $ids
     */
    public static function init(array $ids): self
    {
        return new self(new SaveTracksRequest($ids));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Save Tracks Request object.
     */
    public function build(): SaveTracksRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
