<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\AudiobookObject;
use SpotifyWebApiLib\Models\SavedAudiobookObject;

/**
 * Builder for model SavedAudiobookObject
 *
 * @see SavedAudiobookObject
 */
class SavedAudiobookObjectBuilder
{
    /**
     * @var SavedAudiobookObject
     */
    private $instance;

    private function __construct(SavedAudiobookObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Saved Audiobook Object Builder object.
     */
    public static function init(): self
    {
        return new self(new SavedAudiobookObject());
    }

    /**
     * Sets added at field.
     *
     * @param \DateTime|null $value
     */
    public function addedAt(?\DateTime $value): self
    {
        $this->instance->setAddedAt($value);
        return $this;
    }

    /**
     * Sets audiobook field.
     *
     * @param AudiobookObject|null $value
     */
    public function audiobook(?AudiobookObject $value): self
    {
        $this->instance->setAudiobook($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Saved Audiobook Object object.
     */
    public function build(): SavedAudiobookObject
    {
        return CoreHelper::clone($this->instance);
    }
}
