<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\AlbumObject;
use SpotifyWebApiLib\Models\SavedAlbumObject;

/**
 * Builder for model SavedAlbumObject
 *
 * @see SavedAlbumObject
 */
class SavedAlbumObjectBuilder
{
    /**
     * @var SavedAlbumObject
     */
    private $instance;

    private function __construct(SavedAlbumObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Saved Album Object Builder object.
     */
    public static function init(): self
    {
        return new self(new SavedAlbumObject());
    }

    /**
     * Sets added at field.
     *
     * @param \DateTime|null $value
     */
    public function addedAt(?\DateTime $value): self
    {
        $this->instance->setAddedAt($value);
        return $this;
    }

    /**
     * Sets album field.
     *
     * @param AlbumObject|null $value
     */
    public function album(?AlbumObject $value): self
    {
        $this->instance->setAlbum($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Saved Album Object object.
     */
    public function build(): SavedAlbumObject
    {
        return CoreHelper::clone($this->instance);
    }
}
