<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\SectionObject;

/**
 * Builder for model SectionObject
 *
 * @see SectionObject
 */
class SectionObjectBuilder
{
    /**
     * @var SectionObject
     */
    private $instance;

    private function __construct(SectionObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Section Object Builder object.
     */
    public static function init(): self
    {
        return new self(new SectionObject());
    }

    /**
     * Sets start field.
     *
     * @param float|null $value
     */
    public function start(?float $value): self
    {
        $this->instance->setStart($value);
        return $this;
    }

    /**
     * Sets duration field.
     *
     * @param float|null $value
     */
    public function duration(?float $value): self
    {
        $this->instance->setDuration($value);
        return $this;
    }

    /**
     * Sets confidence field.
     *
     * @param float|null $value
     */
    public function confidence(?float $value): self
    {
        $this->instance->setConfidence($value);
        return $this;
    }

    /**
     * Sets loudness field.
     *
     * @param float|null $value
     */
    public function loudness(?float $value): self
    {
        $this->instance->setLoudness($value);
        return $this;
    }

    /**
     * Sets tempo field.
     *
     * @param float|null $value
     */
    public function tempo(?float $value): self
    {
        $this->instance->setTempo($value);
        return $this;
    }

    /**
     * Sets tempo confidence field.
     *
     * @param float|null $value
     */
    public function tempoConfidence(?float $value): self
    {
        $this->instance->setTempoConfidence($value);
        return $this;
    }

    /**
     * Sets key field.
     *
     * @param int|null $value
     */
    public function key(?int $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Sets key confidence field.
     *
     * @param float|null $value
     */
    public function keyConfidence(?float $value): self
    {
        $this->instance->setKeyConfidence($value);
        return $this;
    }

    /**
     * Sets mode field.
     *
     * @param int|null $value
     */
    public function mode(?int $value): self
    {
        $this->instance->setMode($value);
        return $this;
    }

    /**
     * Sets mode confidence field.
     *
     * @param float|null $value
     */
    public function modeConfidence(?float $value): self
    {
        $this->instance->setModeConfidence($value);
        return $this;
    }

    /**
     * Sets time signature field.
     *
     * @param int|null $value
     */
    public function timeSignature(?int $value): self
    {
        $this->instance->setTimeSignature($value);
        return $this;
    }

    /**
     * Sets time signature confidence field.
     *
     * @param float|null $value
     */
    public function timeSignatureConfidence(?float $value): self
    {
        $this->instance->setTimeSignatureConfidence($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Section Object object.
     */
    public function build(): SectionObject
    {
        return CoreHelper::clone($this->instance);
    }
}
