<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\CopyrightObject;
use SpotifyWebApiLib\Models\ExternalUrlObject;
use SpotifyWebApiLib\Models\ImageObject;
use SpotifyWebApiLib\Models\ShowBase;

/**
 * Builder for model ShowBase
 *
 * @see ShowBase
 */
class ShowBaseBuilder
{
    /**
     * @var ShowBase
     */
    private $instance;

    private function __construct(ShowBase $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Show Base Builder object.
     *
     * @param string[] $availableMarkets
     * @param CopyrightObject[] $copyrights
     * @param string $description
     * @param string $htmlDescription
     * @param bool $explicit
     * @param ExternalUrlObject $externalUrls
     * @param string $href
     * @param string $id
     * @param ImageObject[] $images
     * @param bool $isExternallyHosted
     * @param string[] $languages
     * @param string $mediaType
     * @param string $name
     * @param string $publisher
     * @param string $type
     * @param string $uri
     * @param int $totalEpisodes
     */
    public static function init(
        array $availableMarkets,
        array $copyrights,
        string $description,
        string $htmlDescription,
        bool $explicit,
        ExternalUrlObject $externalUrls,
        string $href,
        string $id,
        array $images,
        bool $isExternallyHosted,
        array $languages,
        string $mediaType,
        string $name,
        string $publisher,
        string $type,
        string $uri,
        int $totalEpisodes
    ): self {
        return new self(new ShowBase(
            $availableMarkets,
            $copyrights,
            $description,
            $htmlDescription,
            $explicit,
            $externalUrls,
            $href,
            $id,
            $images,
            $isExternallyHosted,
            $languages,
            $mediaType,
            $name,
            $publisher,
            $type,
            $uri,
            $totalEpisodes
        ));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Show Base object.
     */
    public function build(): ShowBase
    {
        return CoreHelper::clone($this->instance);
    }
}
