<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\AlbumRestrictionObject;
use SpotifyWebApiLib\Models\ExternalUrlObject;
use SpotifyWebApiLib\Models\ImageObject;
use SpotifyWebApiLib\Models\SimplifiedAlbumObject;
use SpotifyWebApiLib\Models\SimplifiedArtistObject;

/**
 * Builder for model SimplifiedAlbumObject
 *
 * @see SimplifiedAlbumObject
 */
class SimplifiedAlbumObjectBuilder
{
    /**
     * @var SimplifiedAlbumObject
     */
    private $instance;

    private function __construct(SimplifiedAlbumObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Simplified Album Object Builder object.
     *
     * @param string $albumType
     * @param int $totalTracks
     * @param string[] $availableMarkets
     * @param ExternalUrlObject $externalUrls
     * @param string $href
     * @param string $id
     * @param ImageObject[] $images
     * @param string $name
     * @param string $releaseDate
     * @param string $releaseDatePrecision
     * @param string $type
     * @param string $uri
     * @param SimplifiedArtistObject[] $artists
     */
    public static function init(
        string $albumType,
        int $totalTracks,
        array $availableMarkets,
        ExternalUrlObject $externalUrls,
        string $href,
        string $id,
        array $images,
        string $name,
        string $releaseDate,
        string $releaseDatePrecision,
        string $type,
        string $uri,
        array $artists
    ): self {
        return new self(new SimplifiedAlbumObject(
            $albumType,
            $totalTracks,
            $availableMarkets,
            $externalUrls,
            $href,
            $id,
            $images,
            $name,
            $releaseDate,
            $releaseDatePrecision,
            $type,
            $uri,
            $artists
        ));
    }

    /**
     * Sets restrictions field.
     *
     * @param AlbumRestrictionObject|null $value
     */
    public function restrictions(?AlbumRestrictionObject $value): self
    {
        $this->instance->setRestrictions($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Simplified Album Object object.
     */
    public function build(): SimplifiedAlbumObject
    {
        return CoreHelper::clone($this->instance);
    }
}
