<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\StartOrResumePlaybackRequest;

/**
 * Builder for model StartOrResumePlaybackRequest
 *
 * @see StartOrResumePlaybackRequest
 */
class StartOrResumePlaybackRequestBuilder
{
    /**
     * @var StartOrResumePlaybackRequest
     */
    private $instance;

    private function __construct(StartOrResumePlaybackRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Start Or Resume Playback Request Builder object.
     */
    public static function init(): self
    {
        return new self(new StartOrResumePlaybackRequest());
    }

    /**
     * Sets context uri field.
     *
     * @param string|null $value
     */
    public function contextUri(?string $value): self
    {
        $this->instance->setContextUri($value);
        return $this;
    }

    /**
     * Sets uris field.
     *
     * @param string[]|null $value
     */
    public function uris(?array $value): self
    {
        $this->instance->setUris($value);
        return $this;
    }

    /**
     * Sets offset field.
     *
     * @param array|null $value
     */
    public function offset(?array $value): self
    {
        $this->instance->setOffset($value);
        return $this;
    }

    /**
     * Sets position ms field.
     *
     * @param int|null $value
     */
    public function positionMs(?int $value): self
    {
        $this->instance->setPositionMs($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Start Or Resume Playback Request object.
     */
    public function build(): StartOrResumePlaybackRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
