<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\TrackRestrictionObject;

/**
 * Builder for model TrackRestrictionObject
 *
 * @see TrackRestrictionObject
 */
class TrackRestrictionObjectBuilder
{
    /**
     * @var TrackRestrictionObject
     */
    private $instance;

    private function __construct(TrackRestrictionObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Track Restriction Object Builder object.
     */
    public static function init(): self
    {
        return new self(new TrackRestrictionObject());
    }

    /**
     * Sets reason field.
     *
     * @param string|null $value
     */
    public function reason(?string $value): self
    {
        $this->instance->setReason($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Track Restriction Object object.
     */
    public function build(): TrackRestrictionObject
    {
        return CoreHelper::clone($this->instance);
    }
}
