<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\Track1;

/**
 * Builder for model Track1
 *
 * @see Track1
 */
class Track1Builder
{
    /**
     * @var Track1
     */
    private $instance;

    private function __construct(Track1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Track 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Track1());
    }

    /**
     * Sets uri field.
     *
     * @param string|null $value
     */
    public function uri(?string $value): self
    {
        $this->instance->setUri($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Track 1 object.
     */
    public function build(): Track1
    {
        return CoreHelper::clone($this->instance);
    }
}
