<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\ArtistObject;
use SpotifyWebApiLib\Models\ExternalIdObject;
use SpotifyWebApiLib\Models\ExternalUrlObject;
use SpotifyWebApiLib\Models\LinkedTrackObject;
use SpotifyWebApiLib\Models\SimplifiedAlbumObject;
use SpotifyWebApiLib\Models\TrackObject;
use SpotifyWebApiLib\Models\TrackRestrictionObject;

/**
 * Builder for model TrackObject
 *
 * @see TrackObject
 */
class TrackObjectBuilder
{
    /**
     * @var TrackObject
     */
    private $instance;

    private function __construct(TrackObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Track Object Builder object.
     */
    public static function init(): self
    {
        return new self(new TrackObject());
    }

    /**
     * Sets album field.
     *
     * @param SimplifiedAlbumObject|null $value
     */
    public function album(?SimplifiedAlbumObject $value): self
    {
        $this->instance->setAlbum($value);
        return $this;
    }

    /**
     * Sets artists field.
     *
     * @param ArtistObject[]|null $value
     */
    public function artists(?array $value): self
    {
        $this->instance->setArtists($value);
        return $this;
    }

    /**
     * Sets available markets field.
     *
     * @param string[]|null $value
     */
    public function availableMarkets(?array $value): self
    {
        $this->instance->setAvailableMarkets($value);
        return $this;
    }

    /**
     * Sets disc number field.
     *
     * @param int|null $value
     */
    public function discNumber(?int $value): self
    {
        $this->instance->setDiscNumber($value);
        return $this;
    }

    /**
     * Sets duration ms field.
     *
     * @param int|null $value
     */
    public function durationMs(?int $value): self
    {
        $this->instance->setDurationMs($value);
        return $this;
    }

    /**
     * Sets explicit field.
     *
     * @param bool|null $value
     */
    public function explicit(?bool $value): self
    {
        $this->instance->setExplicit($value);
        return $this;
    }

    /**
     * Sets external ids field.
     *
     * @param ExternalIdObject|null $value
     */
    public function externalIds(?ExternalIdObject $value): self
    {
        $this->instance->setExternalIds($value);
        return $this;
    }

    /**
     * Sets external urls field.
     *
     * @param ExternalUrlObject|null $value
     */
    public function externalUrls(?ExternalUrlObject $value): self
    {
        $this->instance->setExternalUrls($value);
        return $this;
    }

    /**
     * Sets href field.
     *
     * @param string|null $value
     */
    public function href(?string $value): self
    {
        $this->instance->setHref($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets is playable field.
     *
     * @param bool|null $value
     */
    public function isPlayable(?bool $value): self
    {
        $this->instance->setIsPlayable($value);
        return $this;
    }

    /**
     * Sets linked from field.
     *
     * @param LinkedTrackObject|null $value
     */
    public function linkedFrom(?LinkedTrackObject $value): self
    {
        $this->instance->setLinkedFrom($value);
        return $this;
    }

    /**
     * Sets restrictions field.
     *
     * @param TrackRestrictionObject|null $value
     */
    public function restrictions(?TrackRestrictionObject $value): self
    {
        $this->instance->setRestrictions($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets popularity field.
     *
     * @param int|null $value
     */
    public function popularity(?int $value): self
    {
        $this->instance->setPopularity($value);
        return $this;
    }

    /**
     * Sets preview url field.
     *
     * @param string|null $value
     */
    public function previewUrl(?string $value): self
    {
        $this->instance->setPreviewUrl($value);
        return $this;
    }

    /**
     * Unsets preview url field.
     */
    public function unsetPreviewUrl(): self
    {
        $this->instance->unsetPreviewUrl();
        return $this;
    }

    /**
     * Sets track number field.
     *
     * @param int|null $value
     */
    public function trackNumber(?int $value): self
    {
        $this->instance->setTrackNumber($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets uri field.
     *
     * @param string|null $value
     */
    public function uri(?string $value): self
    {
        $this->instance->setUri($value);
        return $this;
    }

    /**
     * Sets is local field.
     *
     * @param bool|null $value
     */
    public function isLocal(?bool $value): self
    {
        $this->instance->setIsLocal($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Track Object object.
     */
    public function build(): TrackObject
    {
        return CoreHelper::clone($this->instance);
    }
}
