<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\Track;

/**
 * Builder for model Track
 *
 * @see Track
 */
class TrackBuilder
{
    /**
     * @var Track
     */
    private $instance;

    private function __construct(Track $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Track Builder object.
     */
    public static function init(): self
    {
        return new self(new Track());
    }

    /**
     * Sets num samples field.
     *
     * @param int|null $value
     */
    public function numSamples(?int $value): self
    {
        $this->instance->setNumSamples($value);
        return $this;
    }

    /**
     * Sets duration field.
     *
     * @param float|null $value
     */
    public function duration(?float $value): self
    {
        $this->instance->setDuration($value);
        return $this;
    }

    /**
     * Sets sample md 5 field.
     *
     * @param string|null $value
     */
    public function sampleMd5(?string $value): self
    {
        $this->instance->setSampleMd5($value);
        return $this;
    }

    /**
     * Sets offset seconds field.
     *
     * @param int|null $value
     */
    public function offsetSeconds(?int $value): self
    {
        $this->instance->setOffsetSeconds($value);
        return $this;
    }

    /**
     * Sets window seconds field.
     *
     * @param int|null $value
     */
    public function windowSeconds(?int $value): self
    {
        $this->instance->setWindowSeconds($value);
        return $this;
    }

    /**
     * Sets analysis sample rate field.
     *
     * @param int|null $value
     */
    public function analysisSampleRate(?int $value): self
    {
        $this->instance->setAnalysisSampleRate($value);
        return $this;
    }

    /**
     * Sets analysis channels field.
     *
     * @param int|null $value
     */
    public function analysisChannels(?int $value): self
    {
        $this->instance->setAnalysisChannels($value);
        return $this;
    }

    /**
     * Sets end of fade in field.
     *
     * @param float|null $value
     */
    public function endOfFadeIn(?float $value): self
    {
        $this->instance->setEndOfFadeIn($value);
        return $this;
    }

    /**
     * Sets start of fade out field.
     *
     * @param float|null $value
     */
    public function startOfFadeOut(?float $value): self
    {
        $this->instance->setStartOfFadeOut($value);
        return $this;
    }

    /**
     * Sets loudness field.
     *
     * @param float|null $value
     */
    public function loudness(?float $value): self
    {
        $this->instance->setLoudness($value);
        return $this;
    }

    /**
     * Sets tempo field.
     *
     * @param float|null $value
     */
    public function tempo(?float $value): self
    {
        $this->instance->setTempo($value);
        return $this;
    }

    /**
     * Sets tempo confidence field.
     *
     * @param float|null $value
     */
    public function tempoConfidence(?float $value): self
    {
        $this->instance->setTempoConfidence($value);
        return $this;
    }

    /**
     * Sets time signature field.
     *
     * @param int|null $value
     */
    public function timeSignature(?int $value): self
    {
        $this->instance->setTimeSignature($value);
        return $this;
    }

    /**
     * Sets time signature confidence field.
     *
     * @param float|null $value
     */
    public function timeSignatureConfidence(?float $value): self
    {
        $this->instance->setTimeSignatureConfidence($value);
        return $this;
    }

    /**
     * Sets key field.
     *
     * @param int|null $value
     */
    public function key(?int $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Sets key confidence field.
     *
     * @param float|null $value
     */
    public function keyConfidence(?float $value): self
    {
        $this->instance->setKeyConfidence($value);
        return $this;
    }

    /**
     * Sets mode field.
     *
     * @param int|null $value
     */
    public function mode(?int $value): self
    {
        $this->instance->setMode($value);
        return $this;
    }

    /**
     * Sets mode confidence field.
     *
     * @param float|null $value
     */
    public function modeConfidence(?float $value): self
    {
        $this->instance->setModeConfidence($value);
        return $this;
    }

    /**
     * Sets codestring field.
     *
     * @param string|null $value
     */
    public function codestring(?string $value): self
    {
        $this->instance->setCodestring($value);
        return $this;
    }

    /**
     * Sets code version field.
     *
     * @param float|null $value
     */
    public function codeVersion(?float $value): self
    {
        $this->instance->setCodeVersion($value);
        return $this;
    }

    /**
     * Sets echoprintstring field.
     *
     * @param string|null $value
     */
    public function echoprintstring(?string $value): self
    {
        $this->instance->setEchoprintstring($value);
        return $this;
    }

    /**
     * Sets echoprint version field.
     *
     * @param float|null $value
     */
    public function echoprintVersion(?float $value): self
    {
        $this->instance->setEchoprintVersion($value);
        return $this;
    }

    /**
     * Sets synchstring field.
     *
     * @param string|null $value
     */
    public function synchstring(?string $value): self
    {
        $this->instance->setSynchstring($value);
        return $this;
    }

    /**
     * Sets synch version field.
     *
     * @param float|null $value
     */
    public function synchVersion(?float $value): self
    {
        $this->instance->setSynchVersion($value);
        return $this;
    }

    /**
     * Sets rhythmstring field.
     *
     * @param string|null $value
     */
    public function rhythmstring(?string $value): self
    {
        $this->instance->setRhythmstring($value);
        return $this;
    }

    /**
     * Sets rhythm version field.
     *
     * @param float|null $value
     */
    public function rhythmVersion(?float $value): self
    {
        $this->instance->setRhythmVersion($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Track object.
     */
    public function build(): Track
    {
        return CoreHelper::clone($this->instance);
    }
}
