<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Models\UsersPlaylistsRequest;

/**
 * Builder for model UsersPlaylistsRequest
 *
 * @see UsersPlaylistsRequest
 */
class UsersPlaylistsRequestBuilder
{
    /**
     * @var UsersPlaylistsRequest
     */
    private $instance;

    private function __construct(UsersPlaylistsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Users Playlists Request Builder object.
     *
     * @param string $name
     */
    public static function init(string $name): self
    {
        return new self(new UsersPlaylistsRequest($name));
    }

    /**
     * Sets public field.
     *
     * @param bool|null $value
     */
    public function public(?bool $value): self
    {
        $this->instance->setPublic($value);
        return $this;
    }

    /**
     * Sets collaborative field.
     *
     * @param bool|null $value
     */
    public function collaborative(?bool $value): self
    {
        $this->instance->setCollaborative($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Users Playlists Request object.
     */
    public function build(): UsersPlaylistsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
