<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Apis;

use Core\Request\Parameters\BodyParam;
use Core\Request\Parameters\HeaderParam;
use Core\Request\Parameters\QueryParam;
use Core\Request\Parameters\TemplateParam;
use Core\Response\Types\ErrorType;
use CoreInterfaces\Core\Request\RequestMethod;
use SpotifyWebApiLib\Exceptions\Forbidden1Exception;
use SpotifyWebApiLib\Exceptions\TooManyRequests1Exception;
use SpotifyWebApiLib\Exceptions\Unauthorized1Exception;
use SpotifyWebApiLib\Http\ApiResponse;
use SpotifyWebApiLib\Models\CursorPagedArtists;
use SpotifyWebApiLib\Models\FollowArtistsOrUsersRequest;
use SpotifyWebApiLib\Models\ItemType1;
use SpotifyWebApiLib\Models\ItemType2;
use SpotifyWebApiLib\Models\ItemType3;
use SpotifyWebApiLib\Models\PagingArtistObject;
use SpotifyWebApiLib\Models\PagingTrackObject;
use SpotifyWebApiLib\Models\PlaylistsFollowersRequest;
use SpotifyWebApiLib\Models\PrivateUserObject;
use SpotifyWebApiLib\Models\PublicUserObject;
use SpotifyWebApiLib\Models\UnfollowArtistsOrUsersRequest;

class UsersApi extends BaseApi
{
    /**
     * Get detailed profile information about the current user (including the
     * current user's username).
     *
     *
     * @return ApiResponse Response from the API call
     */
    public function getCurrentUsersProfile(): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/me')->auth('oauth_2_0');

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '401',
                ErrorType::init(
                    "Bad or expired token. This can happen if the user revoked a token or\nthe " .
                    "access token has expired. You should re-authenticate the user.",
                    Unauthorized1Exception::class
                )
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). " .
                    "Unfortunately, re-authenticating the user won't help here.",
                    Forbidden1Exception::class
                )
            )
            ->throwErrorOn(
                '429',
                ErrorType::init('The app has exceeded its rate limits.', TooManyRequests1Exception::class)
            )
            ->type(PrivateUserObject::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Get public profile information about a Spotify user.
     *
     *
     * @param string $userId
     *
     * @return ApiResponse Response from the API call
     */
    public function getUsersProfile(string $userId): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/users/{user_id}')
            ->auth('oauth_2_0')
            ->parameters(TemplateParam::init('user_id', $userId)->required());

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '401',
                ErrorType::init(
                    "Bad or expired token. This can happen if the user revoked a token or\nthe " .
                    "access token has expired. You should re-authenticate the user.",
                    Unauthorized1Exception::class
                )
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). " .
                    "Unfortunately, re-authenticating the user won't help here.",
                    Forbidden1Exception::class
                )
            )
            ->throwErrorOn(
                '429',
                ErrorType::init('The app has exceeded its rate limits.', TooManyRequests1Exception::class)
            )
            ->type(PublicUserObject::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Add the current user as a follower of a playlist.
     *
     *
     * @param string $playlistId
     * @param PlaylistsFollowersRequest|null $body
     *
     * @return ApiResponse Response from the API call
     */
    public function followPlaylist(string $playlistId, ?PlaylistsFollowersRequest $body = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::PUT, '/playlists/{playlist_id}/followers')
            ->auth('oauth_2_0')
            ->parameters(
                TemplateParam::init('playlist_id', $playlistId)->required(),
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '401',
                ErrorType::init(
                    "Bad or expired token. This can happen if the user revoked a token or\nthe " .
                    "access token has expired. You should re-authenticate the user.",
                    Unauthorized1Exception::class
                )
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). " .
                    "Unfortunately, re-authenticating the user won't help here.",
                    Forbidden1Exception::class
                )
            )
            ->throwErrorOn(
                '429',
                ErrorType::init('The app has exceeded its rate limits.', TooManyRequests1Exception::class)
            )
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Remove the current user as a follower of a playlist.
     *
     *
     * @param string $playlistId
     *
     * @return ApiResponse Response from the API call
     */
    public function unfollowPlaylist(string $playlistId): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::DELETE, '/playlists/{playlist_id}/followers')
            ->auth('oauth_2_0')
            ->parameters(TemplateParam::init('playlist_id', $playlistId)->required());

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '401',
                ErrorType::init(
                    "Bad or expired token. This can happen if the user revoked a token or\nthe " .
                    "access token has expired. You should re-authenticate the user.",
                    Unauthorized1Exception::class
                )
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). " .
                    "Unfortunately, re-authenticating the user won't help here.",
                    Forbidden1Exception::class
                )
            )
            ->throwErrorOn(
                '429',
                ErrorType::init('The app has exceeded its rate limits.', TooManyRequests1Exception::class)
            )
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Get the current user's followed artists.
     *
     *
     * @param string $type
     * @param string|null $after
     * @param int|null $limit
     *
     * @return ApiResponse Response from the API call
     */
    public function getFollowed(string $type, ?string $after = null, ?int $limit = 20): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/me/following')
            ->auth('oauth_2_0')
            ->parameters(
                QueryParam::init('type', $type)->required()->serializeBy([ItemType1::class, 'checkValue']),
                QueryParam::init('after', $after),
                QueryParam::init('limit', $limit)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '401',
                ErrorType::init(
                    "Bad or expired token. This can happen if the user revoked a token or\nthe " .
                    "access token has expired. You should re-authenticate the user.",
                    Unauthorized1Exception::class
                )
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). " .
                    "Unfortunately, re-authenticating the user won't help here.",
                    Forbidden1Exception::class
                )
            )
            ->throwErrorOn(
                '429',
                ErrorType::init('The app has exceeded its rate limits.', TooManyRequests1Exception::class)
            )
            ->type(CursorPagedArtists::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Add the current user as a follower of one or more artists or other Spotify users.
     *
     *
     * @param string $type
     * @param string $ids
     * @param FollowArtistsOrUsersRequest|null $body
     *
     * @return ApiResponse Response from the API call
     */
    public function followArtistsUsers(
        string $type,
        string $ids,
        ?FollowArtistsOrUsersRequest $body = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::PUT, '/me/following')
            ->auth('oauth_2_0')
            ->parameters(
                QueryParam::init('type', $type)->required()->serializeBy([ItemType2::class, 'checkValue']),
                QueryParam::init('ids', $ids)->required(),
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '401',
                ErrorType::init(
                    "Bad or expired token. This can happen if the user revoked a token or\nthe " .
                    "access token has expired. You should re-authenticate the user.",
                    Unauthorized1Exception::class
                )
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). " .
                    "Unfortunately, re-authenticating the user won't help here.",
                    Forbidden1Exception::class
                )
            )
            ->throwErrorOn(
                '429',
                ErrorType::init('The app has exceeded its rate limits.', TooManyRequests1Exception::class)
            )
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Remove the current user as a follower of one or more artists or other Spotify users.
     *
     *
     * @param string $type
     * @param string $ids
     * @param UnfollowArtistsOrUsersRequest|null $body
     *
     * @return ApiResponse Response from the API call
     */
    public function unfollowArtistsUsers(
        string $type,
        string $ids,
        ?UnfollowArtistsOrUsersRequest $body = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::DELETE, '/me/following')
            ->auth('oauth_2_0')
            ->parameters(
                QueryParam::init('type', $type)->required()->serializeBy([ItemType3::class, 'checkValue']),
                QueryParam::init('ids', $ids)->required(),
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '401',
                ErrorType::init(
                    "Bad or expired token. This can happen if the user revoked a token or\nthe " .
                    "access token has expired. You should re-authenticate the user.",
                    Unauthorized1Exception::class
                )
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). " .
                    "Unfortunately, re-authenticating the user won't help here.",
                    Forbidden1Exception::class
                )
            )
            ->throwErrorOn(
                '429',
                ErrorType::init('The app has exceeded its rate limits.', TooManyRequests1Exception::class)
            )
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Check to see if the current user is following one or more artists or other Spotify users.
     *
     *
     * @param string $type
     * @param string $ids
     *
     * @return ApiResponse Response from the API call
     */
    public function checkCurrentUserFollows(string $type, string $ids): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/me/following/contains')
            ->auth('oauth_2_0')
            ->parameters(
                QueryParam::init('type', $type)->required()->serializeBy([ItemType3::class, 'checkValue']),
                QueryParam::init('ids', $ids)->required()
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '401',
                ErrorType::init(
                    "Bad or expired token. This can happen if the user revoked a token or\nthe " .
                    "access token has expired. You should re-authenticate the user.",
                    Unauthorized1Exception::class
                )
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). " .
                    "Unfortunately, re-authenticating the user won't help here.",
                    Forbidden1Exception::class
                )
            )
            ->throwErrorOn(
                '429',
                ErrorType::init('The app has exceeded its rate limits.', TooManyRequests1Exception::class)
            )
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Check to see if one or more Spotify users are following a specified playlist.
     *
     *
     * @param string $playlistId
     * @param string $ids
     *
     * @return ApiResponse Response from the API call
     */
    public function checkIfUserFollowsPlaylist(string $playlistId, string $ids): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/playlists/{playlist_id}/followers/contains')
            ->auth('oauth_2_0')
            ->parameters(
                TemplateParam::init('playlist_id', $playlistId)->required(),
                QueryParam::init('ids', $ids)->required()
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '401',
                ErrorType::init(
                    "Bad or expired token. This can happen if the user revoked a token or\nthe " .
                    "access token has expired. You should re-authenticate the user.",
                    Unauthorized1Exception::class
                )
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). " .
                    "Unfortunately, re-authenticating the user won't help here.",
                    Forbidden1Exception::class
                )
            )
            ->throwErrorOn(
                '429',
                ErrorType::init('The app has exceeded its rate limits.', TooManyRequests1Exception::class)
            )
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Get the current user's top artists based on calculated affinity.
     *
     *
     * @param string|null $timeRange
     * @param int|null $limit
     * @param int|null $offset
     *
     * @return ApiResponse Response from the API call
     */
    public function getUsersTopArtists(
        ?string $timeRange = 'medium_term',
        ?int $limit = 20,
        ?int $offset = 0
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/me/top/artists')
            ->auth('oauth_2_0')
            ->parameters(
                QueryParam::init('time_range', $timeRange),
                QueryParam::init('limit', $limit),
                QueryParam::init('offset', $offset)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '401',
                ErrorType::init(
                    "Bad or expired token. This can happen if the user revoked a token or\nthe " .
                    "access token has expired. You should re-authenticate the user.",
                    Unauthorized1Exception::class
                )
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). " .
                    "Unfortunately, re-authenticating the user won't help here.",
                    Forbidden1Exception::class
                )
            )
            ->throwErrorOn(
                '429',
                ErrorType::init('The app has exceeded its rate limits.', TooManyRequests1Exception::class)
            )
            ->type(PagingArtistObject::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * Get the current user's top tracks based on calculated affinity.
     *
     *
     * @param string|null $timeRange
     * @param int|null $limit
     * @param int|null $offset
     *
     * @return ApiResponse Response from the API call
     */
    public function getUsersTopTracks(
        ?string $timeRange = 'medium_term',
        ?int $limit = 20,
        ?int $offset = 0
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/me/top/tracks')
            ->auth('oauth_2_0')
            ->parameters(
                QueryParam::init('time_range', $timeRange),
                QueryParam::init('limit', $limit),
                QueryParam::init('offset', $offset)
            );

        $_resHandler = $this->responseHandler()
            ->throwErrorOn(
                '401',
                ErrorType::init(
                    "Bad or expired token. This can happen if the user revoked a token or\nthe " .
                    "access token has expired. You should re-authenticate the user.",
                    Unauthorized1Exception::class
                )
            )
            ->throwErrorOn(
                '403',
                ErrorType::init(
                    "Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). " .
                    "Unfortunately, re-authenticating the user won't help here.",
                    Forbidden1Exception::class
                )
            )
            ->throwErrorOn(
                '429',
                ErrorType::init('The app has exceeded its rate limits.', TooManyRequests1Exception::class)
            )
            ->type(PagingTrackObject::class)
            ->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
