<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Exceptions;

use SpotifyWebApiLib\ApiHelper;

class NotFound1Exception extends ApiException
{
    /**
     * @var \SpotifyWebApiLib\Models\ErrorObject
     */
    private $error;

    /**
     * @param string $reason
     * @param \SpotifyWebApiLib\Http\HttpRequest $request
     * @param \SpotifyWebApiLib\Http\HttpResponse $response
     * @param \SpotifyWebApiLib\Models\ErrorObject $error
     */
    public function __construct(
        string $reason,
        \SpotifyWebApiLib\Http\HttpRequest $request,
        \SpotifyWebApiLib\Http\HttpResponse $response,
        \SpotifyWebApiLib\Models\ErrorObject $error
    ) {
        parent::__construct($reason, $request, $response);
        $this->error = $error;
    }

    /**
     * Returns Error.
     */
    public function getError(): \SpotifyWebApiLib\Models\ErrorObject
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @required
     * @maps error
     */
    public function setError(\SpotifyWebApiLib\Models\ErrorObject $error): void
    {
        $this->error = $error;
    }

    /**
     * Converts the NotFound1Exception object to a human-readable string representation.
     *
     * @return string The string representation of the NotFound1Exception object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'NotFound1Exception',
            ['error' => $this->error, 'additionalProperties' => $this->additionalProperties],
            parent::__toString()
        );
    }

    protected $propertyNames = ['error'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }
}
