<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class ArtistObject implements \JsonSerializable
{
    /**
     * @var ExternalUrlObject|null
     */
    private $externalUrls;

    /**
     * @var FollowersObject|null
     */
    private $followers;

    /**
     * @var string[]|null
     */
    private $genres;

    /**
     * @var string|null
     */
    private $href;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var ImageObject[]|null
     */
    private $images;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var int|null
     */
    private $popularity;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $uri;

    /**
     * Returns External Urls.
     */
    public function getExternalUrls(): ?ExternalUrlObject
    {
        return $this->externalUrls;
    }

    /**
     * Sets External Urls.
     *
     * @maps external_urls
     */
    public function setExternalUrls(?ExternalUrlObject $externalUrls): void
    {
        $this->externalUrls = $externalUrls;
    }

    /**
     * Returns Followers.
     */
    public function getFollowers(): ?FollowersObject
    {
        return $this->followers;
    }

    /**
     * Sets Followers.
     *
     * @maps followers
     */
    public function setFollowers(?FollowersObject $followers): void
    {
        $this->followers = $followers;
    }

    /**
     * Returns Genres.
     * A list of the genres the artist is associated with. If not yet classified, the array is empty.
     *
     * @return string[]|null
     */
    public function getGenres(): ?array
    {
        return $this->genres;
    }

    /**
     * Sets Genres.
     * A list of the genres the artist is associated with. If not yet classified, the array is empty.
     *
     * @maps genres
     *
     * @param string[]|null $genres
     */
    public function setGenres(?array $genres): void
    {
        $this->genres = $genres;
    }

    /**
     * Returns Href.
     * A link to the Web API endpoint providing full details of the artist.
     */
    public function getHref(): ?string
    {
        return $this->href;
    }

    /**
     * Sets Href.
     * A link to the Web API endpoint providing full details of the artist.
     *
     * @maps href
     */
    public function setHref(?string $href): void
    {
        $this->href = $href;
    }

    /**
     * Returns Id.
     * The [Spotify ID](https://developer.spotify.com/documentation/web-api/concepts/spotify-uris-ids) for
     * the artist.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The [Spotify ID](https://developer.spotify.com/documentation/web-api/concepts/spotify-uris-ids) for
     * the artist.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Images.
     * Images of the artist in various sizes, widest first.
     *
     * @return ImageObject[]|null
     */
    public function getImages(): ?array
    {
        return $this->images;
    }

    /**
     * Sets Images.
     * Images of the artist in various sizes, widest first.
     *
     * @maps images
     *
     * @param ImageObject[]|null $images
     */
    public function setImages(?array $images): void
    {
        $this->images = $images;
    }

    /**
     * Returns Name.
     * The name of the artist.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of the artist.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Popularity.
     * The popularity of the artist. The value will be between 0 and 100, with 100 being the most popular.
     * The artist's popularity is calculated from the popularity of all the artist's tracks.
     */
    public function getPopularity(): ?int
    {
        return $this->popularity;
    }

    /**
     * Sets Popularity.
     * The popularity of the artist. The value will be between 0 and 100, with 100 being the most popular.
     * The artist's popularity is calculated from the popularity of all the artist's tracks.
     *
     * @maps popularity
     */
    public function setPopularity(?int $popularity): void
    {
        $this->popularity = $popularity;
    }

    /**
     * Returns Type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps type
     * @factory \SpotifyWebApiLib\Models\Type::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Uri.
     * The [Spotify URI](https://developer.spotify.com/documentation/web-api/concepts/spotify-uris-ids) for
     * the artist.
     */
    public function getUri(): ?string
    {
        return $this->uri;
    }

    /**
     * Sets Uri.
     * The [Spotify URI](https://developer.spotify.com/documentation/web-api/concepts/spotify-uris-ids) for
     * the artist.
     *
     * @maps uri
     */
    public function setUri(?string $uri): void
    {
        $this->uri = $uri;
    }

    /**
     * Converts the ArtistObject object to a human-readable string representation.
     *
     * @return string The string representation of the ArtistObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ArtistObject',
            [
                'externalUrls' => $this->externalUrls,
                'followers' => $this->followers,
                'genres' => $this->genres,
                'href' => $this->href,
                'id' => $this->id,
                'images' => $this->images,
                'name' => $this->name,
                'popularity' => $this->popularity,
                'type' => $this->type,
                'uri' => $this->uri,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'external_urls',
        'followers',
        'genres',
        'href',
        'id',
        'images',
        'name',
        'popularity',
        'type',
        'uri'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->externalUrls)) {
            $json['external_urls'] = $this->externalUrls;
        }
        if (isset($this->followers)) {
            $json['followers']     = $this->followers;
        }
        if (isset($this->genres)) {
            $json['genres']        = $this->genres;
        }
        if (isset($this->href)) {
            $json['href']          = $this->href;
        }
        if (isset($this->id)) {
            $json['id']            = $this->id;
        }
        if (isset($this->images)) {
            $json['images']        = $this->images;
        }
        if (isset($this->name)) {
            $json['name']          = $this->name;
        }
        if (isset($this->popularity)) {
            $json['popularity']    = $this->popularity;
        }
        if (isset($this->type)) {
            $json['type']          = Type::checkValue($this->type);
        }
        if (isset($this->uri)) {
            $json['uri']           = $this->uri;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
