<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class CategoryObject implements \JsonSerializable
{
    /**
     * @var string
     */
    private $href;

    /**
     * @var ImageObject[]
     */
    private $icons;

    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @param string $href
     * @param ImageObject[] $icons
     * @param string $id
     * @param string $name
     */
    public function __construct(string $href, array $icons, string $id, string $name)
    {
        $this->href = $href;
        $this->icons = $icons;
        $this->id = $id;
        $this->name = $name;
    }

    /**
     * Returns Href.
     * A link to the Web API endpoint returning full details of the category.
     */
    public function getHref(): string
    {
        return $this->href;
    }

    /**
     * Sets Href.
     * A link to the Web API endpoint returning full details of the category.
     *
     * @required
     * @maps href
     */
    public function setHref(string $href): void
    {
        $this->href = $href;
    }

    /**
     * Returns Icons.
     * The category icon, in various sizes.
     *
     * @return ImageObject[]
     */
    public function getIcons(): array
    {
        return $this->icons;
    }

    /**
     * Sets Icons.
     * The category icon, in various sizes.
     *
     * @required
     * @maps icons
     *
     * @param ImageObject[] $icons
     */
    public function setIcons(array $icons): void
    {
        $this->icons = $icons;
    }

    /**
     * Returns Id.
     * The [Spotify category ID](https://developer.spotify.com/documentation/web-api/concepts/spotify-uris-
     * ids) of the category.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The [Spotify category ID](https://developer.spotify.com/documentation/web-api/concepts/spotify-uris-
     * ids) of the category.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Name.
     * The name of the category.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of the category.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Converts the CategoryObject object to a human-readable string representation.
     *
     * @return string The string representation of the CategoryObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CategoryObject',
            [
                'href' => $this->href,
                'icons' => $this->icons,
                'id' => $this->id,
                'name' => $this->name,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['href', 'icons', 'id', 'name'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['href']  = $this->href;
        $json['icons'] = $this->icons;
        $json['id']    = $this->id;
        $json['name']  = $this->name;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
