<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class CurrentlyPlayingObject implements \JsonSerializable
{
    /**
     * @var ContextObject|null
     */
    private $context;

    /**
     * @var int|null
     */
    private $timestamp;

    /**
     * @var int|null
     */
    private $progressMs;

    /**
     * @var bool|null
     */
    private $isPlaying;

    /**
     * @var TrackObject|EpisodeObject|null
     */
    private $item;

    /**
     * @var string|null
     */
    private $currentlyPlayingType;

    /**
     * @var DisallowsObject|null
     */
    private $actions;

    /**
     * Returns Context.
     */
    public function getContext(): ?ContextObject
    {
        return $this->context;
    }

    /**
     * Sets Context.
     *
     * @maps context
     */
    public function setContext(?ContextObject $context): void
    {
        $this->context = $context;
    }

    /**
     * Returns Timestamp.
     * Unix Millisecond Timestamp when data was fetched
     */
    public function getTimestamp(): ?int
    {
        return $this->timestamp;
    }

    /**
     * Sets Timestamp.
     * Unix Millisecond Timestamp when data was fetched
     *
     * @maps timestamp
     */
    public function setTimestamp(?int $timestamp): void
    {
        $this->timestamp = $timestamp;
    }

    /**
     * Returns Progress Ms.
     * Progress into the currently playing track or episode. Can be `null`.
     */
    public function getProgressMs(): ?int
    {
        return $this->progressMs;
    }

    /**
     * Sets Progress Ms.
     * Progress into the currently playing track or episode. Can be `null`.
     *
     * @maps progress_ms
     */
    public function setProgressMs(?int $progressMs): void
    {
        $this->progressMs = $progressMs;
    }

    /**
     * Returns Is Playing.
     * If something is currently playing, return `true`.
     */
    public function getIsPlaying(): ?bool
    {
        return $this->isPlaying;
    }

    /**
     * Sets Is Playing.
     * If something is currently playing, return `true`.
     *
     * @maps is_playing
     */
    public function setIsPlaying(?bool $isPlaying): void
    {
        $this->isPlaying = $isPlaying;
    }

    /**
     * Returns Item.
     * The currently playing track or episode. Can be `null`.
     *
     * @return TrackObject|EpisodeObject|null
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * Sets Item.
     * The currently playing track or episode. Can be `null`.
     *
     * @maps item
     * @mapsBy anyOf(oneOf(TrackObject,EpisodeObject),null)
     *
     * @param TrackObject|EpisodeObject|null $item
     */
    public function setItem($item): void
    {
        $this->item = $item;
    }

    /**
     * Returns Currently Playing Type.
     * The object type of the currently playing item. Can be one of `track`, `episode`, `ad` or `unknown`.
     */
    public function getCurrentlyPlayingType(): ?string
    {
        return $this->currentlyPlayingType;
    }

    /**
     * Sets Currently Playing Type.
     * The object type of the currently playing item. Can be one of `track`, `episode`, `ad` or `unknown`.
     *
     * @maps currently_playing_type
     */
    public function setCurrentlyPlayingType(?string $currentlyPlayingType): void
    {
        $this->currentlyPlayingType = $currentlyPlayingType;
    }

    /**
     * Returns Actions.
     */
    public function getActions(): ?DisallowsObject
    {
        return $this->actions;
    }

    /**
     * Sets Actions.
     *
     * @maps actions
     */
    public function setActions(?DisallowsObject $actions): void
    {
        $this->actions = $actions;
    }

    /**
     * Converts the CurrentlyPlayingObject object to a human-readable string representation.
     *
     * @return string The string representation of the CurrentlyPlayingObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CurrentlyPlayingObject',
            [
                'context' => $this->context,
                'timestamp' => $this->timestamp,
                'progressMs' => $this->progressMs,
                'isPlaying' => $this->isPlaying,
                'item' => $this->item,
                'currentlyPlayingType' => $this->currentlyPlayingType,
                'actions' => $this->actions,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'context',
        'timestamp',
        'progress_ms',
        'is_playing',
        'item',
        'currently_playing_type',
        'actions'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->context)) {
            $json['context']                = $this->context;
        }
        if (isset($this->timestamp)) {
            $json['timestamp']              = $this->timestamp;
        }
        if (isset($this->progressMs)) {
            $json['progress_ms']            = $this->progressMs;
        }
        if (isset($this->isPlaying)) {
            $json['is_playing']             = $this->isPlaying;
        }
        if (isset($this->item)) {
            $json['item']                   =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->item,
                    'anyOf(oneOf(TrackObject,EpisodeObject),null)'
                );
        }
        if (isset($this->currentlyPlayingType)) {
            $json['currently_playing_type'] = $this->currentlyPlayingType;
        }
        if (isset($this->actions)) {
            $json['actions']                = $this->actions;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
