<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class CursorObject implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $after;

    /**
     * @var string|null
     */
    private $before;

    /**
     * Returns After.
     * The cursor to use as key to find the next page of items.
     */
    public function getAfter(): ?string
    {
        return $this->after;
    }

    /**
     * Sets After.
     * The cursor to use as key to find the next page of items.
     *
     * @maps after
     */
    public function setAfter(?string $after): void
    {
        $this->after = $after;
    }

    /**
     * Returns Before.
     * The cursor to use as key to find the previous page of items.
     */
    public function getBefore(): ?string
    {
        return $this->before;
    }

    /**
     * Sets Before.
     * The cursor to use as key to find the previous page of items.
     *
     * @maps before
     */
    public function setBefore(?string $before): void
    {
        $this->before = $before;
    }

    /**
     * Converts the CursorObject object to a human-readable string representation.
     *
     * @return string The string representation of the CursorObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CursorObject',
            [
                'after' => $this->after,
                'before' => $this->before,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['after', 'before'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->after)) {
            $json['after']  = $this->after;
        }
        if (isset($this->before)) {
            $json['before'] = $this->before;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
