<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class ErrorObject implements \JsonSerializable
{
    /**
     * @var int
     */
    private $status;

    /**
     * @var string
     */
    private $message;

    /**
     * @param int $status
     * @param string $message
     */
    public function __construct(int $status, string $message)
    {
        $this->status = $status;
        $this->message = $message;
    }

    /**
     * Returns Status.
     * The HTTP status code (also returned in the response header; see [Response Status Codes](https:
     * //developer.spotify.com/documentation/web-api/concepts/api-calls#response-status-codes) for more
     * information).
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The HTTP status code (also returned in the response header; see [Response Status Codes](https:
     * //developer.spotify.com/documentation/web-api/concepts/api-calls#response-status-codes) for more
     * information).
     *
     * @required
     * @maps status
     */
    public function setStatus(int $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Message.
     * A short description of the cause of the error.
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     * A short description of the cause of the error.
     *
     * @required
     * @maps message
     */
    public function setMessage(string $message): void
    {
        $this->message = $message;
    }

    /**
     * Converts the ErrorObject object to a human-readable string representation.
     *
     * @return string The string representation of the ErrorObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ErrorObject',
            [
                'status' => $this->status,
                'message' => $this->message,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['status', 'message'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['status']  = $this->status;
        $json['message'] = $this->message;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
