<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class ExternalIdObject implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $isrc;

    /**
     * @var string|null
     */
    private $ean;

    /**
     * @var string|null
     */
    private $upc;

    /**
     * Returns Isrc.
     * [International Standard Recording Code](http://en.wikipedia.
     * org/wiki/International_Standard_Recording_Code)
     */
    public function getIsrc(): ?string
    {
        return $this->isrc;
    }

    /**
     * Sets Isrc.
     * [International Standard Recording Code](http://en.wikipedia.
     * org/wiki/International_Standard_Recording_Code)
     *
     * @maps isrc
     */
    public function setIsrc(?string $isrc): void
    {
        $this->isrc = $isrc;
    }

    /**
     * Returns Ean.
     * [International Article Number](http://en.wikipedia.org/wiki/International_Article_Number_%28EAN%29)
     */
    public function getEan(): ?string
    {
        return $this->ean;
    }

    /**
     * Sets Ean.
     * [International Article Number](http://en.wikipedia.org/wiki/International_Article_Number_%28EAN%29)
     *
     * @maps ean
     */
    public function setEan(?string $ean): void
    {
        $this->ean = $ean;
    }

    /**
     * Returns Upc.
     * [Universal Product Code](http://en.wikipedia.org/wiki/Universal_Product_Code)
     */
    public function getUpc(): ?string
    {
        return $this->upc;
    }

    /**
     * Sets Upc.
     * [Universal Product Code](http://en.wikipedia.org/wiki/Universal_Product_Code)
     *
     * @maps upc
     */
    public function setUpc(?string $upc): void
    {
        $this->upc = $upc;
    }

    /**
     * Converts the ExternalIdObject object to a human-readable string representation.
     *
     * @return string The string representation of the ExternalIdObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ExternalIdObject',
            [
                'isrc' => $this->isrc,
                'ean' => $this->ean,
                'upc' => $this->upc,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['isrc', 'ean', 'upc'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->isrc)) {
            $json['isrc'] = $this->isrc;
        }
        if (isset($this->ean)) {
            $json['ean']  = $this->ean;
        }
        if (isset($this->upc)) {
            $json['upc']  = $this->upc;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
