<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class FollowersObject implements \JsonSerializable
{
    /**
     * @var array
     */
    private $href = [];

    /**
     * @var int|null
     */
    private $total;

    /**
     * Returns Href.
     * This will always be set to null, as the Web API does not support it at the moment.
     */
    public function getHref(): ?string
    {
        if (count($this->href) == 0) {
            return null;
        }
        return $this->href['value'];
    }

    /**
     * Sets Href.
     * This will always be set to null, as the Web API does not support it at the moment.
     *
     * @maps href
     */
    public function setHref(?string $href): void
    {
        $this->href['value'] = $href;
    }

    /**
     * Unsets Href.
     * This will always be set to null, as the Web API does not support it at the moment.
     */
    public function unsetHref(): void
    {
        $this->href = [];
    }

    /**
     * Returns Total.
     * The total number of followers.
     */
    public function getTotal(): ?int
    {
        return $this->total;
    }

    /**
     * Sets Total.
     * The total number of followers.
     *
     * @maps total
     */
    public function setTotal(?int $total): void
    {
        $this->total = $total;
    }

    /**
     * Converts the FollowersObject object to a human-readable string representation.
     *
     * @return string The string representation of the FollowersObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'FollowersObject',
            [
                'href' => $this->getHref(),
                'total' => $this->total,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['href', 'total'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->href)) {
            $json['href']  = $this->href['value'];
        }
        if (isset($this->total)) {
            $json['total'] = $this->total;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
