<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class ImageObject implements \JsonSerializable
{
    /**
     * @var string
     */
    private $url;

    /**
     * @var int|null
     */
    private $height;

    /**
     * @var int|null
     */
    private $width;

    /**
     * @param string $url
     */
    public function __construct(string $url)
    {
        $this->url = $url;
    }

    /**
     * Returns Url.
     * The source URL of the image.
     */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     * The source URL of the image.
     *
     * @required
     * @maps url
     */
    public function setUrl(string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns Height.
     * The image height in pixels.
     */
    public function getHeight(): ?int
    {
        return $this->height;
    }

    /**
     * Sets Height.
     * The image height in pixels.
     *
     * @maps height
     */
    public function setHeight(?int $height): void
    {
        $this->height = $height;
    }

    /**
     * Returns Width.
     * The image width in pixels.
     */
    public function getWidth(): ?int
    {
        return $this->width;
    }

    /**
     * Sets Width.
     * The image width in pixels.
     *
     * @maps width
     */
    public function setWidth(?int $width): void
    {
        $this->width = $width;
    }

    /**
     * Converts the ImageObject object to a human-readable string representation.
     *
     * @return string The string representation of the ImageObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ImageObject',
            [
                'url' => $this->url,
                'height' => $this->height,
                'width' => $this->width,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['url', 'height', 'width'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['url']    = $this->url;
        $json['height'] = $this->height;
        $json['width']  = $this->width;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
