<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class ManyAlbums implements \JsonSerializable
{
    /**
     * @var AlbumObject[]
     */
    private $albums;

    /**
     * @param AlbumObject[] $albums
     */
    public function __construct(array $albums)
    {
        $this->albums = $albums;
    }

    /**
     * Returns Albums.
     *
     * @return AlbumObject[]
     */
    public function getAlbums(): array
    {
        return $this->albums;
    }

    /**
     * Sets Albums.
     *
     * @required
     * @maps albums
     *
     * @param AlbumObject[] $albums
     */
    public function setAlbums(array $albums): void
    {
        $this->albums = $albums;
    }

    /**
     * Converts the ManyAlbums object to a human-readable string representation.
     *
     * @return string The string representation of the ManyAlbums object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ManyAlbums',
            ['albums' => $this->albums, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['albums'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['albums'] = $this->albums;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
