<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use SpotifyWebApiLib\Utils\DateTimeHelper;
use stdClass;

class PlaylistTrackObject implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $addedAt;

    /**
     * @var PlaylistUserObject|null
     */
    private $addedBy;

    /**
     * @var bool|null
     */
    private $isLocal;

    /**
     * @var TrackObject|EpisodeObject|null
     */
    private $track;

    /**
     * Returns Added At.
     * The date and time the track or episode was added. _**Note**: some very old playlists may return
     * `null` in this field._
     */
    public function getAddedAt(): ?\DateTime
    {
        return $this->addedAt;
    }

    /**
     * Sets Added At.
     * The date and time the track or episode was added. _**Note**: some very old playlists may return
     * `null` in this field._
     *
     * @maps added_at
     * @factory \SpotifyWebApiLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setAddedAt(?\DateTime $addedAt): void
    {
        $this->addedAt = $addedAt;
    }

    /**
     * Returns Added By.
     */
    public function getAddedBy(): ?PlaylistUserObject
    {
        return $this->addedBy;
    }

    /**
     * Sets Added By.
     *
     * @maps added_by
     */
    public function setAddedBy(?PlaylistUserObject $addedBy): void
    {
        $this->addedBy = $addedBy;
    }

    /**
     * Returns Is Local.
     * Whether this track or episode is a [local file](https://developer.spotify.com/documentation/web-
     * api/concepts/playlists/#local-files) or not.
     */
    public function getIsLocal(): ?bool
    {
        return $this->isLocal;
    }

    /**
     * Sets Is Local.
     * Whether this track or episode is a [local file](https://developer.spotify.com/documentation/web-
     * api/concepts/playlists/#local-files) or not.
     *
     * @maps is_local
     */
    public function setIsLocal(?bool $isLocal): void
    {
        $this->isLocal = $isLocal;
    }

    /**
     * Returns Track.
     * Information about the track or episode.
     *
     * @return TrackObject|EpisodeObject|null
     */
    public function getTrack()
    {
        return $this->track;
    }

    /**
     * Sets Track.
     * Information about the track or episode.
     *
     * @maps track
     * @mapsBy anyOf(oneOf(TrackObject,EpisodeObject),null)
     *
     * @param TrackObject|EpisodeObject|null $track
     */
    public function setTrack($track): void
    {
        $this->track = $track;
    }

    /**
     * Converts the PlaylistTrackObject object to a human-readable string representation.
     *
     * @return string The string representation of the PlaylistTrackObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PlaylistTrackObject',
            [
                'addedAt' => $this->addedAt,
                'addedBy' => $this->addedBy,
                'isLocal' => $this->isLocal,
                'track' => $this->track,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['added_at', 'added_by', 'is_local', 'track'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->addedAt)) {
            $json['added_at'] = DateTimeHelper::toRfc3339DateTime($this->addedAt);
        }
        if (isset($this->addedBy)) {
            $json['added_by'] = $this->addedBy;
        }
        if (isset($this->isLocal)) {
            $json['is_local'] = $this->isLocal;
        }
        if (isset($this->track)) {
            $json['track']    =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->track,
                    'anyOf(oneOf(TrackObject,EpisodeObject),null)'
                );
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
