<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class PlaylistsTracksRequest1 implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $uris;

    /**
     * @var int|null
     */
    private $rangeStart;

    /**
     * @var int|null
     */
    private $insertBefore;

    /**
     * @var int|null
     */
    private $rangeLength;

    /**
     * @var string|null
     */
    private $snapshotId;

    /**
     * Returns Uris.
     *
     * @return string[]|null
     */
    public function getUris(): ?array
    {
        return $this->uris;
    }

    /**
     * Sets Uris.
     *
     * @maps uris
     *
     * @param string[]|null $uris
     */
    public function setUris(?array $uris): void
    {
        $this->uris = $uris;
    }

    /**
     * Returns Range Start.
     * The position of the first item to be reordered.
     */
    public function getRangeStart(): ?int
    {
        return $this->rangeStart;
    }

    /**
     * Sets Range Start.
     * The position of the first item to be reordered.
     *
     * @maps range_start
     */
    public function setRangeStart(?int $rangeStart): void
    {
        $this->rangeStart = $rangeStart;
    }

    /**
     * Returns Insert Before.
     * The position where the items should be inserted.<br/>To reorder the items to the end of the playlist,
     * simply set _insert_before_ to the position after the last item.<br/>Examples:<br/>To reorder the
     * first item to the last position in a playlist with 10 items, set _range_start_ to 0, and
     * _insert_before_ to 10.<br/>To reorder the last item in a playlist with 10 items to the start of the
     * playlist, set _range_start_ to 9, and _insert_before_ to 0.
     */
    public function getInsertBefore(): ?int
    {
        return $this->insertBefore;
    }

    /**
     * Sets Insert Before.
     * The position where the items should be inserted.<br/>To reorder the items to the end of the playlist,
     * simply set _insert_before_ to the position after the last item.<br/>Examples:<br/>To reorder the
     * first item to the last position in a playlist with 10 items, set _range_start_ to 0, and
     * _insert_before_ to 10.<br/>To reorder the last item in a playlist with 10 items to the start of the
     * playlist, set _range_start_ to 9, and _insert_before_ to 0.
     *
     * @maps insert_before
     */
    public function setInsertBefore(?int $insertBefore): void
    {
        $this->insertBefore = $insertBefore;
    }

    /**
     * Returns Range Length.
     * The amount of items to be reordered. Defaults to 1 if not set.<br/>The range of items to be
     * reordered begins from the _range_start_ position, and includes the _range_length_ subsequent items.
     * <br/>Example:<br/>To move the items at index 9-10 to the start of the playlist, _range_start_ is set
     * to 9, and _range_length_ is set to 2.
     */
    public function getRangeLength(): ?int
    {
        return $this->rangeLength;
    }

    /**
     * Sets Range Length.
     * The amount of items to be reordered. Defaults to 1 if not set.<br/>The range of items to be
     * reordered begins from the _range_start_ position, and includes the _range_length_ subsequent items.
     * <br/>Example:<br/>To move the items at index 9-10 to the start of the playlist, _range_start_ is set
     * to 9, and _range_length_ is set to 2.
     *
     * @maps range_length
     */
    public function setRangeLength(?int $rangeLength): void
    {
        $this->rangeLength = $rangeLength;
    }

    /**
     * Returns Snapshot Id.
     * The playlist's snapshot ID against which you want to make the changes.
     */
    public function getSnapshotId(): ?string
    {
        return $this->snapshotId;
    }

    /**
     * Sets Snapshot Id.
     * The playlist's snapshot ID against which you want to make the changes.
     *
     * @maps snapshot_id
     */
    public function setSnapshotId(?string $snapshotId): void
    {
        $this->snapshotId = $snapshotId;
    }

    /**
     * Converts the PlaylistsTracksRequest1 object to a human-readable string representation.
     *
     * @return string The string representation of the PlaylistsTracksRequest1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PlaylistsTracksRequest1',
            [
                'uris' => $this->uris,
                'rangeStart' => $this->rangeStart,
                'insertBefore' => $this->insertBefore,
                'rangeLength' => $this->rangeLength,
                'snapshotId' => $this->snapshotId,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['uris', 'range_start', 'insert_before', 'range_length', 'snapshot_id'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->uris)) {
            $json['uris']          = $this->uris;
        }
        if (isset($this->rangeStart)) {
            $json['range_start']   = $this->rangeStart;
        }
        if (isset($this->insertBefore)) {
            $json['insert_before'] = $this->insertBefore;
        }
        if (isset($this->rangeLength)) {
            $json['range_length']  = $this->rangeLength;
        }
        if (isset($this->snapshotId)) {
            $json['snapshot_id']   = $this->snapshotId;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
