<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class RecommendationSeedObject implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $afterFilteringSize;

    /**
     * @var int|null
     */
    private $afterRelinkingSize;

    /**
     * @var string|null
     */
    private $href;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var int|null
     */
    private $initialPoolSize;

    /**
     * @var string|null
     */
    private $type;

    /**
     * Returns After Filtering Size.
     * The number of tracks available after min\_\* and max\_\* filters have been applied.
     */
    public function getAfterFilteringSize(): ?int
    {
        return $this->afterFilteringSize;
    }

    /**
     * Sets After Filtering Size.
     * The number of tracks available after min\_\* and max\_\* filters have been applied.
     *
     * @maps afterFilteringSize
     */
    public function setAfterFilteringSize(?int $afterFilteringSize): void
    {
        $this->afterFilteringSize = $afterFilteringSize;
    }

    /**
     * Returns After Relinking Size.
     * The number of tracks available after relinking for regional availability.
     */
    public function getAfterRelinkingSize(): ?int
    {
        return $this->afterRelinkingSize;
    }

    /**
     * Sets After Relinking Size.
     * The number of tracks available after relinking for regional availability.
     *
     * @maps afterRelinkingSize
     */
    public function setAfterRelinkingSize(?int $afterRelinkingSize): void
    {
        $this->afterRelinkingSize = $afterRelinkingSize;
    }

    /**
     * Returns Href.
     * A link to the full track or artist data for this seed. For tracks this will be a link to a Track
     * Object. For artists a link to an Artist Object. For genre seeds, this value will be `null`.
     */
    public function getHref(): ?string
    {
        return $this->href;
    }

    /**
     * Sets Href.
     * A link to the full track or artist data for this seed. For tracks this will be a link to a Track
     * Object. For artists a link to an Artist Object. For genre seeds, this value will be `null`.
     *
     * @maps href
     */
    public function setHref(?string $href): void
    {
        $this->href = $href;
    }

    /**
     * Returns Id.
     * The id used to select this seed. This will be the same as the string used in the `seed_artists`,
     * `seed_tracks` or `seed_genres` parameter.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The id used to select this seed. This will be the same as the string used in the `seed_artists`,
     * `seed_tracks` or `seed_genres` parameter.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Initial Pool Size.
     * The number of recommended tracks available for this seed.
     */
    public function getInitialPoolSize(): ?int
    {
        return $this->initialPoolSize;
    }

    /**
     * Sets Initial Pool Size.
     * The number of recommended tracks available for this seed.
     *
     * @maps initialPoolSize
     */
    public function setInitialPoolSize(?int $initialPoolSize): void
    {
        $this->initialPoolSize = $initialPoolSize;
    }

    /**
     * Returns Type.
     * The entity type of this seed. One of `artist`, `track` or `genre`.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The entity type of this seed. One of `artist`, `track` or `genre`.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the RecommendationSeedObject object to a human-readable string representation.
     *
     * @return string The string representation of the RecommendationSeedObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RecommendationSeedObject',
            [
                'afterFilteringSize' => $this->afterFilteringSize,
                'afterRelinkingSize' => $this->afterRelinkingSize,
                'href' => $this->href,
                'id' => $this->id,
                'initialPoolSize' => $this->initialPoolSize,
                'type' => $this->type,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['afterFilteringSize', 'afterRelinkingSize', 'href', 'id', 'initialPoolSize', 'type'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->afterFilteringSize)) {
            $json['afterFilteringSize'] = $this->afterFilteringSize;
        }
        if (isset($this->afterRelinkingSize)) {
            $json['afterRelinkingSize'] = $this->afterRelinkingSize;
        }
        if (isset($this->href)) {
            $json['href']               = $this->href;
        }
        if (isset($this->id)) {
            $json['id']                 = $this->id;
        }
        if (isset($this->initialPoolSize)) {
            $json['initialPoolSize']    = $this->initialPoolSize;
        }
        if (isset($this->type)) {
            $json['type']               = $this->type;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
