<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class RecommendationsObject implements \JsonSerializable
{
    /**
     * @var RecommendationSeedObject[]
     */
    private $seeds;

    /**
     * @var TrackObject[]
     */
    private $tracks;

    /**
     * @param RecommendationSeedObject[] $seeds
     * @param TrackObject[] $tracks
     */
    public function __construct(array $seeds, array $tracks)
    {
        $this->seeds = $seeds;
        $this->tracks = $tracks;
    }

    /**
     * Returns Seeds.
     * An array of recommendation seed objects.
     *
     * @return RecommendationSeedObject[]
     */
    public function getSeeds(): array
    {
        return $this->seeds;
    }

    /**
     * Sets Seeds.
     * An array of recommendation seed objects.
     *
     * @required
     * @maps seeds
     *
     * @param RecommendationSeedObject[] $seeds
     */
    public function setSeeds(array $seeds): void
    {
        $this->seeds = $seeds;
    }

    /**
     * Returns Tracks.
     * An array of track objects ordered according to the parameters supplied.
     *
     * @return TrackObject[]
     */
    public function getTracks(): array
    {
        return $this->tracks;
    }

    /**
     * Sets Tracks.
     * An array of track objects ordered according to the parameters supplied.
     *
     * @required
     * @maps tracks
     *
     * @param TrackObject[] $tracks
     */
    public function setTracks(array $tracks): void
    {
        $this->tracks = $tracks;
    }

    /**
     * Converts the RecommendationsObject object to a human-readable string representation.
     *
     * @return string The string representation of the RecommendationsObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RecommendationsObject',
            [
                'seeds' => $this->seeds,
                'tracks' => $this->tracks,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['seeds', 'tracks'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['seeds']  = $this->seeds;
        $json['tracks'] = $this->tracks;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
