<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class ResumePointObject implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $fullyPlayed;

    /**
     * @var int|null
     */
    private $resumePositionMs;

    /**
     * Returns Fully Played.
     * Whether or not the episode has been fully played by the user.
     */
    public function getFullyPlayed(): ?bool
    {
        return $this->fullyPlayed;
    }

    /**
     * Sets Fully Played.
     * Whether or not the episode has been fully played by the user.
     *
     * @maps fully_played
     */
    public function setFullyPlayed(?bool $fullyPlayed): void
    {
        $this->fullyPlayed = $fullyPlayed;
    }

    /**
     * Returns Resume Position Ms.
     * The user's most recent position in the episode in milliseconds.
     */
    public function getResumePositionMs(): ?int
    {
        return $this->resumePositionMs;
    }

    /**
     * Sets Resume Position Ms.
     * The user's most recent position in the episode in milliseconds.
     *
     * @maps resume_position_ms
     */
    public function setResumePositionMs(?int $resumePositionMs): void
    {
        $this->resumePositionMs = $resumePositionMs;
    }

    /**
     * Converts the ResumePointObject object to a human-readable string representation.
     *
     * @return string The string representation of the ResumePointObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ResumePointObject',
            [
                'fullyPlayed' => $this->fullyPlayed,
                'resumePositionMs' => $this->resumePositionMs,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['fully_played', 'resume_position_ms'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->fullyPlayed)) {
            $json['fully_played']       = $this->fullyPlayed;
        }
        if (isset($this->resumePositionMs)) {
            $json['resume_position_ms'] = $this->resumePositionMs;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
