<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class SaveEpisodesRequest implements \JsonSerializable
{
    /**
     * @var string[]
     */
    private $ids;

    /**
     * @param string[] $ids
     */
    public function __construct(array $ids)
    {
        $this->ids = $ids;
    }

    /**
     * Returns Ids.
     * A JSON array of the [Spotify IDs](https://developer.spotify.com/documentation/web-
     * api/concepts/spotify-uris-ids). <br/>A maximum of 50 items can be specified in one request.
     * _**Note**: if the `ids` parameter is present in the query string, any IDs listed here in the body
     * will be ignored._
     *
     * @return string[]
     */
    public function getIds(): array
    {
        return $this->ids;
    }

    /**
     * Sets Ids.
     * A JSON array of the [Spotify IDs](https://developer.spotify.com/documentation/web-
     * api/concepts/spotify-uris-ids). <br/>A maximum of 50 items can be specified in one request.
     * _**Note**: if the `ids` parameter is present in the query string, any IDs listed here in the body
     * will be ignored._
     *
     * @required
     * @maps ids
     *
     * @param string[] $ids
     */
    public function setIds(array $ids): void
    {
        $this->ids = $ids;
    }

    /**
     * Converts the SaveEpisodesRequest object to a human-readable string representation.
     *
     * @return string The string representation of the SaveEpisodesRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SaveEpisodesRequest',
            ['ids' => $this->ids, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['ids'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['ids'] = $this->ids;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
