<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class SearchItems implements \JsonSerializable
{
    /**
     * @var PagingTrackObject|null
     */
    private $tracks;

    /**
     * @var PagingArtistObject|null
     */
    private $artists;

    /**
     * @var PagingSimplifiedAlbumObject|null
     */
    private $albums;

    /**
     * @var PagingPlaylistObject|null
     */
    private $playlists;

    /**
     * @var PagingSimplifiedShowObject|null
     */
    private $shows;

    /**
     * @var PagingSimplifiedEpisodeObject|null
     */
    private $episodes;

    /**
     * @var PagingSimplifiedAudiobookObject|null
     */
    private $audiobooks;

    /**
     * Returns Tracks.
     */
    public function getTracks(): ?PagingTrackObject
    {
        return $this->tracks;
    }

    /**
     * Sets Tracks.
     *
     * @maps tracks
     */
    public function setTracks(?PagingTrackObject $tracks): void
    {
        $this->tracks = $tracks;
    }

    /**
     * Returns Artists.
     */
    public function getArtists(): ?PagingArtistObject
    {
        return $this->artists;
    }

    /**
     * Sets Artists.
     *
     * @maps artists
     */
    public function setArtists(?PagingArtistObject $artists): void
    {
        $this->artists = $artists;
    }

    /**
     * Returns Albums.
     */
    public function getAlbums(): ?PagingSimplifiedAlbumObject
    {
        return $this->albums;
    }

    /**
     * Sets Albums.
     *
     * @maps albums
     */
    public function setAlbums(?PagingSimplifiedAlbumObject $albums): void
    {
        $this->albums = $albums;
    }

    /**
     * Returns Playlists.
     */
    public function getPlaylists(): ?PagingPlaylistObject
    {
        return $this->playlists;
    }

    /**
     * Sets Playlists.
     *
     * @maps playlists
     */
    public function setPlaylists(?PagingPlaylistObject $playlists): void
    {
        $this->playlists = $playlists;
    }

    /**
     * Returns Shows.
     */
    public function getShows(): ?PagingSimplifiedShowObject
    {
        return $this->shows;
    }

    /**
     * Sets Shows.
     *
     * @maps shows
     */
    public function setShows(?PagingSimplifiedShowObject $shows): void
    {
        $this->shows = $shows;
    }

    /**
     * Returns Episodes.
     */
    public function getEpisodes(): ?PagingSimplifiedEpisodeObject
    {
        return $this->episodes;
    }

    /**
     * Sets Episodes.
     *
     * @maps episodes
     */
    public function setEpisodes(?PagingSimplifiedEpisodeObject $episodes): void
    {
        $this->episodes = $episodes;
    }

    /**
     * Returns Audiobooks.
     */
    public function getAudiobooks(): ?PagingSimplifiedAudiobookObject
    {
        return $this->audiobooks;
    }

    /**
     * Sets Audiobooks.
     *
     * @maps audiobooks
     */
    public function setAudiobooks(?PagingSimplifiedAudiobookObject $audiobooks): void
    {
        $this->audiobooks = $audiobooks;
    }

    /**
     * Converts the SearchItems object to a human-readable string representation.
     *
     * @return string The string representation of the SearchItems object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SearchItems',
            [
                'tracks' => $this->tracks,
                'artists' => $this->artists,
                'albums' => $this->albums,
                'playlists' => $this->playlists,
                'shows' => $this->shows,
                'episodes' => $this->episodes,
                'audiobooks' => $this->audiobooks,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['tracks', 'artists', 'albums', 'playlists', 'shows', 'episodes', 'audiobooks'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->tracks)) {
            $json['tracks']     = $this->tracks;
        }
        if (isset($this->artists)) {
            $json['artists']    = $this->artists;
        }
        if (isset($this->albums)) {
            $json['albums']     = $this->albums;
        }
        if (isset($this->playlists)) {
            $json['playlists']  = $this->playlists;
        }
        if (isset($this->shows)) {
            $json['shows']      = $this->shows;
        }
        if (isset($this->episodes)) {
            $json['episodes']   = $this->episodes;
        }
        if (isset($this->audiobooks)) {
            $json['audiobooks'] = $this->audiobooks;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
