<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class StartOrResumePlaybackRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $contextUri;

    /**
     * @var string[]|null
     */
    private $uris;

    /**
     * @var array|null
     */
    private $offset;

    /**
     * @var int|null
     */
    private $positionMs;

    /**
     * Returns Context Uri.
     * Optional. Spotify URI of the context to play.
     * Valid contexts are albums, artists & playlists.
     * `{context_uri:"spotify:album:1Je1IMUlBXcx1Fz0WE7oPT"}`
     */
    public function getContextUri(): ?string
    {
        return $this->contextUri;
    }

    /**
     * Sets Context Uri.
     * Optional. Spotify URI of the context to play.
     * Valid contexts are albums, artists & playlists.
     * `{context_uri:"spotify:album:1Je1IMUlBXcx1Fz0WE7oPT"}`
     *
     * @maps context_uri
     */
    public function setContextUri(?string $contextUri): void
    {
        $this->contextUri = $contextUri;
    }

    /**
     * Returns Uris.
     * Optional. A JSON array of the Spotify track URIs to play.
     * For example: `{"uris": ["spotify:track:4iV5W9uYEdYUVa79Axb7Rh", "spotify:track:
     * 1301WleyT98MSxVHPZCA6M"]}`
     *
     * @return string[]|null
     */
    public function getUris(): ?array
    {
        return $this->uris;
    }

    /**
     * Sets Uris.
     * Optional. A JSON array of the Spotify track URIs to play.
     * For example: `{"uris": ["spotify:track:4iV5W9uYEdYUVa79Axb7Rh", "spotify:track:
     * 1301WleyT98MSxVHPZCA6M"]}`
     *
     * @maps uris
     *
     * @param string[]|null $uris
     */
    public function setUris(?array $uris): void
    {
        $this->uris = $uris;
    }

    /**
     * Returns Offset.
     * Optional. Indicates from where in the context playback should start. Only available when context_uri
     * corresponds to an album or playlist object
     * "position" is zero based and can’t be negative. Example: `"offset": {"position": 5}`
     * "uri" is a string representing the uri of the item to start at. Example: `"offset": {"uri": "spotify:
     * track:1301WleyT98MSxVHPZCA6M"}`
     */
    public function getOffset(): ?array
    {
        return $this->offset;
    }

    /**
     * Sets Offset.
     * Optional. Indicates from where in the context playback should start. Only available when context_uri
     * corresponds to an album or playlist object
     * "position" is zero based and can’t be negative. Example: `"offset": {"position": 5}`
     * "uri" is a string representing the uri of the item to start at. Example: `"offset": {"uri": "spotify:
     * track:1301WleyT98MSxVHPZCA6M"}`
     *
     * @maps offset
     */
    public function setOffset(?array $offset): void
    {
        $this->offset = $offset;
    }

    /**
     * Returns Position Ms.
     * Indicates from what position to start playback. Must be a positive number. Passing in a position
     * that is greater than the length of the track will cause the player to start playing the next song.
     */
    public function getPositionMs(): ?int
    {
        return $this->positionMs;
    }

    /**
     * Sets Position Ms.
     * Indicates from what position to start playback. Must be a positive number. Passing in a position
     * that is greater than the length of the track will cause the player to start playing the next song.
     *
     * @maps position_ms
     */
    public function setPositionMs(?int $positionMs): void
    {
        $this->positionMs = $positionMs;
    }

    /**
     * Converts the StartOrResumePlaybackRequest object to a human-readable string representation.
     *
     * @return string The string representation of the StartOrResumePlaybackRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'StartOrResumePlaybackRequest',
            [
                'contextUri' => $this->contextUri,
                'uris' => $this->uris,
                'offset' => $this->offset,
                'positionMs' => $this->positionMs,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['context_uri', 'uris', 'offset', 'position_ms'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->contextUri)) {
            $json['context_uri'] = $this->contextUri;
        }
        if (isset($this->uris)) {
            $json['uris']        = $this->uris;
        }
        if (isset($this->offset)) {
            $json['offset']      = $this->offset;
        }
        if (isset($this->positionMs)) {
            $json['position_ms'] = $this->positionMs;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
