<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class TimeIntervalObject implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $start;

    /**
     * @var float|null
     */
    private $duration;

    /**
     * @var float|null
     */
    private $confidence;

    /**
     * Returns Start.
     * The starting point (in seconds) of the time interval.
     */
    public function getStart(): ?float
    {
        return $this->start;
    }

    /**
     * Sets Start.
     * The starting point (in seconds) of the time interval.
     *
     * @maps start
     */
    public function setStart(?float $start): void
    {
        $this->start = $start;
    }

    /**
     * Returns Duration.
     * The duration (in seconds) of the time interval.
     */
    public function getDuration(): ?float
    {
        return $this->duration;
    }

    /**
     * Sets Duration.
     * The duration (in seconds) of the time interval.
     *
     * @maps duration
     */
    public function setDuration(?float $duration): void
    {
        $this->duration = $duration;
    }

    /**
     * Returns Confidence.
     * The confidence, from 0.0 to 1.0, of the reliability of the interval.
     */
    public function getConfidence(): ?float
    {
        return $this->confidence;
    }

    /**
     * Sets Confidence.
     * The confidence, from 0.0 to 1.0, of the reliability of the interval.
     *
     * @maps confidence
     */
    public function setConfidence(?float $confidence): void
    {
        $this->confidence = $confidence;
    }

    /**
     * Converts the TimeIntervalObject object to a human-readable string representation.
     *
     * @return string The string representation of the TimeIntervalObject object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TimeIntervalObject',
            [
                'start' => $this->start,
                'duration' => $this->duration,
                'confidence' => $this->confidence,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['start', 'duration', 'confidence'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->start)) {
            $json['start']      = $this->start;
        }
        if (isset($this->duration)) {
            $json['duration']   = $this->duration;
        }
        if (isset($this->confidence)) {
            $json['confidence'] = $this->confidence;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
