<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib\Models;

use SpotifyWebApiLib\ApiHelper;
use stdClass;

class UsersPlaylistsRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $name;

    /**
     * @var bool|null
     */
    private $public;

    /**
     * @var bool|null
     */
    private $collaborative;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @param string $name
     */
    public function __construct(string $name)
    {
        $this->name = $name;
    }

    /**
     * Returns Name.
     * The name for the new playlist, for example `"Your Coolest Playlist"`. This name does not need to be
     * unique; a user may have several playlists with the same name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name for the new playlist, for example `"Your Coolest Playlist"`. This name does not need to be
     * unique; a user may have several playlists with the same name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Public.
     * Defaults to `true`. If `true` the playlist will be public, if `false` it will be private. To be able
     * to create private playlists, the user must have granted the `playlist-modify-private` [scope](https:
     * //developer.spotify.com/documentation/web-api/concepts/scopes/#list-of-scopes)
     */
    public function getPublic(): ?bool
    {
        return $this->public;
    }

    /**
     * Sets Public.
     * Defaults to `true`. If `true` the playlist will be public, if `false` it will be private. To be able
     * to create private playlists, the user must have granted the `playlist-modify-private` [scope](https:
     * //developer.spotify.com/documentation/web-api/concepts/scopes/#list-of-scopes)
     *
     * @maps public
     */
    public function setPublic(?bool $public): void
    {
        $this->public = $public;
    }

    /**
     * Returns Collaborative.
     * Defaults to `false`. If `true` the playlist will be collaborative. _**Note**: to create a
     * collaborative playlist you must also set `public` to `false`. To create collaborative playlists you
     * must have granted `playlist-modify-private` and `playlist-modify-public` [scopes](https://developer.
     * spotify.com/documentation/web-api/concepts/scopes/#list-of-scopes)._
     */
    public function getCollaborative(): ?bool
    {
        return $this->collaborative;
    }

    /**
     * Sets Collaborative.
     * Defaults to `false`. If `true` the playlist will be collaborative. _**Note**: to create a
     * collaborative playlist you must also set `public` to `false`. To create collaborative playlists you
     * must have granted `playlist-modify-private` and `playlist-modify-public` [scopes](https://developer.
     * spotify.com/documentation/web-api/concepts/scopes/#list-of-scopes)._
     *
     * @maps collaborative
     */
    public function setCollaborative(?bool $collaborative): void
    {
        $this->collaborative = $collaborative;
    }

    /**
     * Returns Description.
     * value for playlist description as displayed in Spotify Clients and in the Web API.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * value for playlist description as displayed in Spotify Clients and in the Web API.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Converts the UsersPlaylistsRequest object to a human-readable string representation.
     *
     * @return string The string representation of the UsersPlaylistsRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'UsersPlaylistsRequest',
            [
                'name' => $this->name,
                'public' => $this->public,
                'collaborative' => $this->collaborative,
                'description' => $this->description,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['name', 'public', 'collaborative', 'description'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['name']              = $this->name;
        if (isset($this->public)) {
            $json['public']        = $this->public;
        }
        if (isset($this->collaborative)) {
            $json['collaborative'] = $this->collaborative;
        }
        if (isset($this->description)) {
            $json['description']   = $this->description;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
