<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib;

/**
 * Environments available for API
 */
class Environment
{
    public const PRODUCTION = 'production';

    public const ENVIRONMENT2 = 'environment2';
}
