<?php

declare(strict_types=1);

/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpotifyWebApiLib;

use Core\ClientBuilder;
use Core\Utils\CoreHelper;
use SpotifyWebApiLib\Apis\AlbumsApi;
use SpotifyWebApiLib\Apis\ArtistsApi;
use SpotifyWebApiLib\Apis\AudiobooksApi;
use SpotifyWebApiLib\Apis\CategoriesApi;
use SpotifyWebApiLib\Apis\ChaptersApi;
use SpotifyWebApiLib\Apis\EpisodesApi;
use SpotifyWebApiLib\Apis\GenresApi;
use SpotifyWebApiLib\Apis\MarketsApi;
use SpotifyWebApiLib\Apis\OauthAuthorizationApi;
use SpotifyWebApiLib\Apis\PlayerApi;
use SpotifyWebApiLib\Apis\PlaylistsApi;
use SpotifyWebApiLib\Apis\SearchApi;
use SpotifyWebApiLib\Apis\ShowsApi;
use SpotifyWebApiLib\Apis\TracksApi;
use SpotifyWebApiLib\Apis\UsersApi;
use SpotifyWebApiLib\Authentication\AuthorizationCodeAuthCredentialsBuilder;
use SpotifyWebApiLib\Authentication\AuthorizationCodeAuthManager;
use SpotifyWebApiLib\Logging\LoggingConfigurationBuilder;
use SpotifyWebApiLib\Logging\RequestLoggingConfigurationBuilder;
use SpotifyWebApiLib\Logging\ResponseLoggingConfigurationBuilder;
use SpotifyWebApiLib\Proxy\ProxyConfigurationBuilder;
use SpotifyWebApiLib\Utils\CompatibilityConverter;
use Unirest\Configuration;
use Unirest\HttpClient;

class SpotifyWebApiClient implements ConfigurationInterface
{
    private $albums;

    private $artists;

    private $audiobooks;

    private $categories;

    private $chapters;

    private $episodes;

    private $genres;

    private $markets;

    private $player;

    private $playlists;

    private $search;

    private $shows;

    private $tracks;

    private $users;

    private $oauthAuthorization;

    private $authorizationCodeAuthManager;

    private $loggingConfigurationBuilder;

    private $proxyConfiguration;

    private $config;

    private $client;

    /**
     * @see SpotifyWebApiClientBuilder::init()
     * @see SpotifyWebApiClientBuilder::build()
     *
     * @param array $config
     */
    public function __construct(array $config = [])
    {
        $this->config = array_merge(ConfigurationDefaults::_ALL, CoreHelper::clone($config));
        $this->authorizationCodeAuthManager = new AuthorizationCodeAuthManager($this->config);
        $this->validateConfig();
        $loggingConfiguration = null;
        if ($this->config['loggingConfiguration'] instanceof LoggingConfigurationBuilder) {
            $this->loggingConfigurationBuilder = $this->config['loggingConfiguration'];
            $loggingConfiguration = $this->loggingConfigurationBuilder->build();
        }
        $this->proxyConfiguration = $this->config['proxyConfiguration'] ?? ConfigurationDefaults::PROXY_CONFIGURATION;
        $this->client = ClientBuilder::init(
            new HttpClient(Configuration::init($this)->proxyConfiguration($this->proxyConfiguration))
        )
            ->converter(new CompatibilityConverter())
            ->jsonHelper(ApiHelper::getJsonHelper())
            ->apiCallback($this->config['httpCallback'] ?? null)
            ->userAgent('PHP-SDK/2024.3.3 (OS: {os-info}, Engine: {engine}/{engine-version})')
            ->serverUrls(self::ENVIRONMENT_MAP[$this->getEnvironment()], Server::DEFAULT_)
            ->authManagers(['oauth_2_0' => $this->authorizationCodeAuthManager])
            ->loggingConfiguration($loggingConfiguration)
            ->build();
        $this->authorizationCodeAuthManager->setClient($this->client);
    }

    /**
     * Create a builder with the current client's configurations.
     *
     * @return SpotifyWebApiClientBuilder SpotifyWebApiClientBuilder instance
     */
    public function toBuilder(): SpotifyWebApiClientBuilder
    {
        $builder = SpotifyWebApiClientBuilder::init()
            ->timeout($this->getTimeout())
            ->enableRetries($this->shouldEnableRetries())
            ->numberOfRetries($this->getNumberOfRetries())
            ->retryInterval($this->getRetryInterval())
            ->backOffFactor($this->getBackOffFactor())
            ->maximumRetryWaitTime($this->getMaximumRetryWaitTime())
            ->retryOnTimeout($this->shouldRetryOnTimeout())
            ->httpStatusCodesToRetry($this->getHttpStatusCodesToRetry())
            ->httpMethodsToRetry($this->getHttpMethodsToRetry())
            ->environment($this->getEnvironment())
            ->httpCallback($this->config['httpCallback'] ?? null)
            ->proxyConfiguration($this->getProxyConfigurationBuilder());

        $authorizationCodeAuth = $this->getAuthorizationCodeAuthCredentialsBuilder();
        if ($authorizationCodeAuth != null) {
            $builder->authorizationCodeAuthCredentials($authorizationCodeAuth);
        }
        $loggingConfigurationBuilder = $this->getLoggingConfigurationBuilder();
        if ($loggingConfigurationBuilder != null) {
            $builder->loggingConfiguration($loggingConfigurationBuilder);
        }
        return $builder;
    }

    public function getTimeout(): int
    {
        return $this->config['timeout'] ?? ConfigurationDefaults::TIMEOUT;
    }

    public function shouldEnableRetries(): bool
    {
        return $this->config['enableRetries'] ?? ConfigurationDefaults::ENABLE_RETRIES;
    }

    public function getNumberOfRetries(): int
    {
        return $this->config['numberOfRetries'] ?? ConfigurationDefaults::NUMBER_OF_RETRIES;
    }

    public function getRetryInterval(): float
    {
        return $this->config['retryInterval'] ?? ConfigurationDefaults::RETRY_INTERVAL;
    }

    public function getBackOffFactor(): float
    {
        return $this->config['backOffFactor'] ?? ConfigurationDefaults::BACK_OFF_FACTOR;
    }

    public function getMaximumRetryWaitTime(): int
    {
        return $this->config['maximumRetryWaitTime'] ?? ConfigurationDefaults::MAXIMUM_RETRY_WAIT_TIME;
    }

    public function shouldRetryOnTimeout(): bool
    {
        return $this->config['retryOnTimeout'] ?? ConfigurationDefaults::RETRY_ON_TIMEOUT;
    }

    public function getHttpStatusCodesToRetry(): array
    {
        return $this->config['httpStatusCodesToRetry'] ?? ConfigurationDefaults::HTTP_STATUS_CODES_TO_RETRY;
    }

    public function getHttpMethodsToRetry(): array
    {
        return $this->config['httpMethodsToRetry'] ?? ConfigurationDefaults::HTTP_METHODS_TO_RETRY;
    }

    public function getEnvironment(): string
    {
        return $this->config['environment'] ?? ConfigurationDefaults::ENVIRONMENT;
    }

    public function getAuthorizationCodeAuth(): AuthorizationCodeAuth
    {
        return $this->authorizationCodeAuthManager;
    }

    public function getAuthorizationCodeAuthCredentialsBuilder(): ?AuthorizationCodeAuthCredentialsBuilder
    {
        if (
            empty($this->authorizationCodeAuthManager->getOauthClientId()) &&
            empty($this->authorizationCodeAuthManager->getOauthClientSecret()) &&
            empty($this->authorizationCodeAuthManager->getOauthRedirectUri())
        ) {
            return null;
        }
        return AuthorizationCodeAuthCredentialsBuilder::init(
            $this->authorizationCodeAuthManager->getOauthClientId(),
            $this->authorizationCodeAuthManager->getOauthClientSecret(),
            $this->authorizationCodeAuthManager->getOauthRedirectUri()
        )
            ->oauthToken($this->authorizationCodeAuthManager->getOauthToken())
            ->oauthScopes($this->authorizationCodeAuthManager->getOauthScopes());
    }

    public function getLoggingConfigurationBuilder(): ?LoggingConfigurationBuilder
    {
        if (is_null($this->loggingConfigurationBuilder)) {
            return null;
        }
        $config = $this->loggingConfigurationBuilder->getConfiguration();
        return LoggingConfigurationBuilder::init()
            ->level($config['level'])
            ->logger($config['logger'])
            ->maskSensitiveHeaders($config['maskSensitiveHeaders'])
            ->requestConfiguration(RequestLoggingConfigurationBuilder::init()
                ->includeQueryInPath($config['requestConfiguration']['includeQueryInPath'])
                ->body($config['requestConfiguration']['body'])
                ->headers($config['requestConfiguration']['headers'])
                ->includeHeaders(...$config['requestConfiguration']['includeHeaders'])
                ->excludeHeaders(...$config['requestConfiguration']['excludeHeaders'])
                ->unmaskHeaders(...$config['requestConfiguration']['unmaskHeaders']))
            ->responseConfiguration(ResponseLoggingConfigurationBuilder::init()
                ->body($config['responseConfiguration']['body'])
                ->headers($config['responseConfiguration']['headers'])
                ->includeHeaders(...$config['responseConfiguration']['includeHeaders'])
                ->excludeHeaders(...$config['responseConfiguration']['excludeHeaders'])
                ->unmaskHeaders(...$config['responseConfiguration']['unmaskHeaders']));
    }

    /**
     * Get the proxy configuration builder
     */
    public function getProxyConfigurationBuilder(): ProxyConfigurationBuilder
    {
        return ProxyConfigurationBuilder::init($this->proxyConfiguration['address'])
            ->port($this->proxyConfiguration['port'])
            ->tunnel($this->proxyConfiguration['tunnel'])
            ->auth($this->proxyConfiguration['auth']['user'], $this->proxyConfiguration['auth']['pass'])
            ->authMethod($this->proxyConfiguration['auth']['method']);
    }

    /**
     * Get the client configuration as an associative array
     *
     * @see SpotifyWebApiClientBuilder::getConfiguration()
     */
    public function getConfiguration(): array
    {
        return $this->toBuilder()->getConfiguration();
    }

    /**
     * Clone this client and override given configuration options
     *
     * @see SpotifyWebApiClientBuilder::build()
     */
    public function withConfiguration(array $config): self
    {
        return new self(array_merge($this->config, $config));
    }

    /**
     * Validate required configuration variables
     */
    private function validateConfig(): void
    {
        $builder = SpotifyWebApiClientBuilder::init();

        $authorizationCodeAuth = $this->getAuthorizationCodeAuthCredentialsBuilder();
        if ($authorizationCodeAuth != null) {
            $builder->authorizationCodeAuthCredentials($authorizationCodeAuth);
        }
    }

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string
    {
        return $this->client->getGlobalRequest($server)->getQueryUrl();
    }

    /**
     * Returns Albums Api
     */
    public function getAlbumsApi(): AlbumsApi
    {
        if ($this->albums == null) {
            $this->albums = new AlbumsApi($this->client);
        }
        return $this->albums;
    }

    /**
     * Returns Artists Api
     */
    public function getArtistsApi(): ArtistsApi
    {
        if ($this->artists == null) {
            $this->artists = new ArtistsApi($this->client);
        }
        return $this->artists;
    }

    /**
     * Returns Audiobooks Api
     */
    public function getAudiobooksApi(): AudiobooksApi
    {
        if ($this->audiobooks == null) {
            $this->audiobooks = new AudiobooksApi($this->client);
        }
        return $this->audiobooks;
    }

    /**
     * Returns Categories Api
     */
    public function getCategoriesApi(): CategoriesApi
    {
        if ($this->categories == null) {
            $this->categories = new CategoriesApi($this->client);
        }
        return $this->categories;
    }

    /**
     * Returns Chapters Api
     */
    public function getChaptersApi(): ChaptersApi
    {
        if ($this->chapters == null) {
            $this->chapters = new ChaptersApi($this->client);
        }
        return $this->chapters;
    }

    /**
     * Returns Episodes Api
     */
    public function getEpisodesApi(): EpisodesApi
    {
        if ($this->episodes == null) {
            $this->episodes = new EpisodesApi($this->client);
        }
        return $this->episodes;
    }

    /**
     * Returns Genres Api
     */
    public function getGenresApi(): GenresApi
    {
        if ($this->genres == null) {
            $this->genres = new GenresApi($this->client);
        }
        return $this->genres;
    }

    /**
     * Returns Markets Api
     */
    public function getMarketsApi(): MarketsApi
    {
        if ($this->markets == null) {
            $this->markets = new MarketsApi($this->client);
        }
        return $this->markets;
    }

    /**
     * Returns Player Api
     */
    public function getPlayerApi(): PlayerApi
    {
        if ($this->player == null) {
            $this->player = new PlayerApi($this->client);
        }
        return $this->player;
    }

    /**
     * Returns Playlists Api
     */
    public function getPlaylistsApi(): PlaylistsApi
    {
        if ($this->playlists == null) {
            $this->playlists = new PlaylistsApi($this->client);
        }
        return $this->playlists;
    }

    /**
     * Returns Search Api
     */
    public function getSearchApi(): SearchApi
    {
        if ($this->search == null) {
            $this->search = new SearchApi($this->client);
        }
        return $this->search;
    }

    /**
     * Returns Shows Api
     */
    public function getShowsApi(): ShowsApi
    {
        if ($this->shows == null) {
            $this->shows = new ShowsApi($this->client);
        }
        return $this->shows;
    }

    /**
     * Returns Tracks Api
     */
    public function getTracksApi(): TracksApi
    {
        if ($this->tracks == null) {
            $this->tracks = new TracksApi($this->client);
        }
        return $this->tracks;
    }

    /**
     * Returns Users Api
     */
    public function getUsersApi(): UsersApi
    {
        if ($this->users == null) {
            $this->users = new UsersApi($this->client);
        }
        return $this->users;
    }

    /**
     * Returns Oauth Authorization Api
     */
    public function getOauthAuthorizationApi(): OauthAuthorizationApi
    {
        if ($this->oauthAuthorization == null) {
            $this->oauthAuthorization = new OauthAuthorizationApi($this->client);
        }
        return $this->oauthAuthorization;
    }

    /**
     * A map of all base urls used in different environments and servers
     *
     * @var array
     */
    private const ENVIRONMENT_MAP = [
        Environment::PRODUCTION => [Server::DEFAULT_ => 'https://api.spotify.com/v1'],
        Environment::ENVIRONMENT2 => [Server::DEFAULT_ => 'https://accounts.spotify.com']
    ];
}
